import type { ReportFeedItem, CommentItem, StoryItem, ScopeOption } from "./types";

// ─── Media URLs — Unsplash (free, no attribution required) ───────────────────
// All images: object-cover ready, 800×600 crop
// Videos: autoplay muted loop playsInline

export const ORIGINAL_MOCK_FEED: ReportFeedItem[] = [
  {
    id: "r1",
    userName: "Rahul M.",
    userInitial: "R",
    userColor: "#3B82F6",
    isAnonymous: false,
    isVerified: true,
    isFollowing: false,
    location: "Andheri West, Mumbai",
    road: "SV Road near Flyover",
    timeAgo: "2h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "critical",
    title: "Large pothole causing accidents near Andheri Station flyover",
    description:
      "This pothole is 2ft wide, 8 inches deep. Two bikes fell here this week. Municipality unresponsive for 3 weeks. Depth increases every rain.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=85",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 91,
    trustScore: 87,
    verificationPercent: 94,
    authorityStatus: "Assigned — BMC Mumbai",
    verifiedCitizensCount: 38,

    status: "in_progress",
    statusStep: 3,
    upvotes: 247,
    hasUpvoted: false,
    comments: 43,
    shares: 255,
    saves: 2487,
    views: 12400,
    isSaved: false,
    officialResponse: true,
    coordinates: { lat: 19.1197, lng: 72.8464 },
  },

  {
    id: "r2",
    userName: "Sneha D.",
    userInitial: "S",
    userColor: "#22C55E",
    isAnonymous: false,
    isVerified: true,
    isFollowing: true,
    location: "Bandra West, Mumbai",
    road: "Hill Road near Lucky Junction",
    timeAgo: "4h ago",
    hazardType: "flooding",
    hazardEmoji: "🌊",
    severity: "high",
    title: "Severe waterlogging blocking entire road after heavy rain",
    description:
      "Water level rose 3 feet in just 2 hours. Multiple vehicles stranded. Drainage completely blocked by garbage. Kids unable to reach school.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "video",
    mediaUrl:
      "https://cdn.pixabay.com/video/2020/07/31/46404-446298818_large.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 78,
    trustScore: 92,
    verificationPercent: 89,
    authorityStatus: "In Review — BMC Ward Office",
    verifiedCitizensCount: 61,

    status: "verified",
    statusStep: 2,
    upvotes: 589,
    hasUpvoted: true,
    comments: 78,
    shares: 412,
    saves: 1890,
    views: 23500,
    isSaved: true,
    officialResponse: true,
    coordinates: { lat: 19.0544, lng: 72.8277 },
  },

  {
    id: "r3",
    userName: "Amit P.",
    userInitial: "A",
    userColor: "#F59E0B",
    isAnonymous: false,
    isVerified: false,
    isFollowing: false,
    location: "Dadar East, Mumbai",
    road: "Tulsi Pipe Road",
    timeAgo: "6h ago",
    hazardType: "broken-signal",
    hazardEmoji: "🚦",
    severity: "medium",
    title: "Traffic signal completely non-functional at major junction",
    description:
      "Signal has been dead for 48 hours. No traffic police present during peak hours. Multiple near-misses observed. Evening rush hour is chaos.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?auto=format&fit=crop&w=800&q=85",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 64,
    trustScore: 71,
    verificationPercent: 68,
    authorityStatus: "Pending — Traffic Police HQ",
    verifiedCitizensCount: 14,

    status: "submitted",
    statusStep: 1,
    upvotes: 134,
    hasUpvoted: false,
    comments: 21,
    shares: 67,
    saves: 445,
    views: 5600,
    isSaved: false,
    officialResponse: false,
    coordinates: { lat: 19.0178, lng: 72.8478 },
  },

  {
    id: "r4",
    userName: "Kavita N.",
    userInitial: "K",
    userColor: "#8B5CF6",
    isAnonymous: false,
    isVerified: true,
    isFollowing: true,
    location: "Borivali West, Mumbai",
    road: "S.V. Road near Rajendra Nagar",
    timeAgo: "12h ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "low",
    title: "Construction debris dumped on footpath blocking pedestrian access",
    description:
      "Builder has dumped rubble from construction site on the main footpath. Pedestrians forced to walk on road. Elderly & wheelchair users most affected.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=85",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 42,
    trustScore: 88,
    verificationPercent: 100,
    authorityStatus: "Resolved — BMC Borivali",
    verifiedCitizensCount: 9,

    status: "resolved",
    statusStep: 5,
    upvotes: 89,
    hasUpvoted: false,
    comments: 12,
    shares: 34,
    saves: 156,
    views: 3200,
    isSaved: false,
    officialResponse: true,
    coordinates: { lat: 19.2307, lng: 72.8567 },
  },

  {
    id: "r5",
    userName: "Anonymous",
    userInitial: "?",
    userColor: "#6B7280",
    isAnonymous: true,
    isVerified: false,
    isFollowing: false,
    location: "Kurla West, Mumbai",
    road: "LBS Marg near Kurla Station",
    timeAgo: "1h ago",
    hazardType: "accident",
    hazardEmoji: "💥",
    severity: "critical",
    title: "Major accident zone — broken divider causing head-on collisions",
    description:
      "Divider broken since last week. 3 accidents in 2 days. Nobody from BMC has come to repair. Extremely dangerous at night with no street lighting.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "video",
    mediaUrl:
      "https://cdn.pixabay.com/video/2016/09/08/5068-182856752_large.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 96,
    trustScore: 79,
    verificationPercent: 82,
    authorityStatus: "Escalated — Mumbai Police + BMC",
    verifiedCitizensCount: 104,

    status: "in_progress",
    statusStep: 3,
    upvotes: 712,
    hasUpvoted: false,
    comments: 156,
    shares: 890,
    saves: 4200,
    views: 45000,
    isSaved: false,
    officialResponse: true,
    coordinates: { lat: 19.0726, lng: 72.8794 },
  },

  {
    id: "r6",
    userName: "Priya S.",
    userInitial: "P",
    userColor: "#EC4899",
    isAnonymous: false,
    isVerified: true,
    isFollowing: false,
    location: "Kothrud, Pune",
    road: "Karve Road near MIT College",
    timeAgo: "3h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "high",
    title: "Deep pothole near MIT College gate causing daily accidents",
    description:
      "Students are getting injured daily. Pothole appeared after last monsoon and keeps growing. PMC has ignored 5 complaints over 3 months.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1560782205-4dd83ceb0270?auto=format&fit=crop&w=800&q=85",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1560782205-4dd83ceb0270?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 74,
    trustScore: 85,
    verificationPercent: 77,
    authorityStatus: "Pending — PMC Kothrud Division",
    verifiedCitizensCount: 29,

    status: "verified",
    statusStep: 2,
    upvotes: 345,
    hasUpvoted: false,
    comments: 67,
    shares: 234,
    saves: 1200,
    views: 18000,
    isSaved: false,
    officialResponse: false,
    coordinates: { lat: 18.5074, lng: 73.8077 },
  },

  {
    id: "r7",
    userName: "Vikram R.",
    userInitial: "V",
    userColor: "#06B6D4",
    isAnonymous: false,
    isVerified: false,
    isFollowing: false,
    location: "Dharampeth, Nagpur",
    road: "Central Avenue Road",
    timeAgo: "8h ago",
    hazardType: "waterlogging",
    hazardEmoji: "💧",
    severity: "high",
    title: "Chronic waterlogging at central avenue — sewage overflow",
    description:
      "Every rain causes sewage to overflow here. Stench is unbearable. Health hazard for nearby residents and shopkeepers. Reported thrice this year.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1601128533718-374ffcca299b?auto=format&fit=crop&w=800&q=85",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1601128533718-374ffcca299b?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 69,
    trustScore: 66,
    verificationPercent: 58,
    authorityStatus: "Pending — Nagpur Municipal Corporation",
    verifiedCitizensCount: 17,

    status: "submitted",
    statusStep: 1,
    upvotes: 167,
    hasUpvoted: false,
    comments: 34,
    shares: 78,
    saves: 560,
    views: 7800,
    isSaved: false,
    officialResponse: false,
    coordinates: { lat: 21.1458, lng: 79.0882 },
  },

  {
    id: "r8",
    userName: "Deepak T.",
    userInitial: "D",
    userColor: "#EF4444",
    isAnonymous: false,
    isVerified: true,
    isFollowing: true,
    location: "NH-48, Vasai",
    road: "Mumbai-Ahmedabad Highway",
    timeAgo: "5h ago",
    hazardType: "guardrail",
    hazardEmoji: "🛡️",
    severity: "critical",
    title: "Broken guardrail on highway — vehicles going off road at night",
    description:
      "50m section of guardrail missing after truck crash. No warning signs installed. 2 cars went off road last night. Immediate NHAI action needed.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=800&q=85",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 88,
    trustScore: 91,
    verificationPercent: 86,
    authorityStatus: "Assigned — NHAI Vasai Division",
    verifiedCitizensCount: 47,

    status: "in_progress",
    statusStep: 3,
    upvotes: 423,
    hasUpvoted: false,
    comments: 89,
    shares: 567,
    saves: 3100,
    views: 34000,
    isSaved: false,
    officialResponse: true,
    coordinates: { lat: 19.3607, lng: 72.8397 },
  },

  {
    id: "r9",
    userName: "Neha J.",
    userInitial: "N",
    userColor: "#10B981",
    isAnonymous: false,
    isVerified: false,
    isFollowing: false,
    location: "Andheri East, Mumbai",
    road: "MIDC Road near Chakala",
    timeAgo: "1d ago",
    hazardType: "street-light",
    hazardEmoji: "💡",
    severity: "low",
    title: "8 consecutive street lights non-functional — pitch dark after 7pm",
    description:
      "Entire stretch is completely dark after sunset. Women feel unsafe walking here. Two chain-snatching incidents reported this week. Reported thrice.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1476820865390-c52aeebb9891?auto=format&fit=crop&w=800&q=85",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1476820865390-c52aeebb9891?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 55,
    trustScore: 73,
    verificationPercent: 61,
    authorityStatus: "Pending — MSEDCL Andheri",
    verifiedCitizensCount: 22,

    status: "verified",
    statusStep: 2,
    upvotes: 198,
    hasUpvoted: false,
    comments: 28,
    shares: 89,
    saves: 670,
    views: 9200,
    isSaved: false,
    officialResponse: false,
    coordinates: { lat: 19.1136, lng: 72.8697 },
  },

  {
    id: "r10",
    userName: "Suresh K.",
    userInitial: "S",
    userColor: "#F97316",
    isAnonymous: false,
    isVerified: true,
    isFollowing: false,
    location: "Thane West, Mumbai",
    road: "Ghodbunder Road",
    timeAgo: "30m ago",
    hazardType: "cave-in",
    hazardEmoji: "🕳",
    severity: "critical",
    title: "Road cave-in on Ghodbunder Road — entire lane collapsed",
    description:
      "Major cave-in 10ft wide. Underground pipe burst caused the collapse. Traffic diverted but no barricades placed. I heard the collapse from my apartment at 3 AM.",

    // ── Media ──────────────────────────────────────────────────────
    mediaType: "video",
    mediaUrl:
      "https://cdn.pixabay.com/video/2020/03/25/34444-402088612_large.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1624138784614-87fd1b6528f8?auto=format&fit=crop&w=400&q=70",

    // ── Intelligence Scores ────────────────────────────────────────
    riskScore: 98,
    trustScore: 95,
    verificationPercent: 97,
    authorityStatus: "Emergency — Thane MC + PWD On-Site",
    verifiedCitizensCount: 183,

    status: "in_progress",
    statusStep: 4,
    upvotes: 891,
    hasUpvoted: false,
    comments: 234,
    shares: 1200,
    saves: 5600,
    views: 67000,
    isSaved: false,
    officialResponse: true,
    coordinates: { lat: 19.2183, lng: 72.9781 },
  },
];

// ─── Comments (unchanged — realistic already) ────────────────────────────────

export const ORIGINAL_MOCK_COMMENTS: Record<string, CommentItem[]> = {
  r1: [
    { id: "c1", userName: "Priya K.", initial: "P", color: "#22C55E", text: "Confirmed! Almost damaged my scooter here yesterday evening 😔", likes: 34, timeAgo: "2h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c2", userName: "BMC Mumbai", initial: "B", color: "#3B82F6", text: "We have logged this (Ref: BMC-2026-4821). Repair team assigned, ETA 48 hours.", likes: 89, timeAgo: "1h", isOfficial: true, isPinned: true, replies: [
      { id: "r1", userName: "Rahul M.", text: "Thank you! Please prioritize this 🙏", likes: 12, timeAgo: "45m" },
      { id: "r2", userName: "Priya K.", text: "Finally some response. Hope they actually fix it this time.", likes: 8, timeAgo: "30m" },
    ] },
    { id: "c3", userName: "Amit S.", initial: "A", color: "#F59E0B", text: "I reported this 2 weeks ago too. Nothing happened then. Glad it is getting attention now.", likes: 56, timeAgo: "3h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c4", userName: "Meera R.", initial: "M", color: "#EC4899", text: "Same pothole caused a rickshaw to tip over yesterday. Driver got injured 😢", likes: 45, timeAgo: "4h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c5", userName: "Deepak V.", initial: "D", color: "#8B5CF6", text: "This entire stretch is horrible. Not just this one pothole.", likes: 23, timeAgo: "5h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c6", userName: "Sanjay P.", initial: "S", color: "#06B6D4", text: "I use this road daily. Have to zigzag like crazy. Total nightmare.", likes: 19, timeAgo: "5h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c7", userName: "Nisha T.", initial: "N", color: "#10B981", text: "Put a barricade at least! Someone will die here.", likes: 67, timeAgo: "6h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c8", userName: "Rajesh B.", initial: "R", color: "#F97316", text: "Shared this on WhatsApp groups. Let us make this viral 🔥", likes: 28, timeAgo: "6h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c9", userName: "Traffic Police", initial: "TP", color: "#3B82F6", text: "We are aware of the situation. Advisory issued for commuters to use alternate route.", likes: 43, timeAgo: "7h", isOfficial: true, isPinned: false, replies: [] },
    { id: "c10", userName: "Kishore M.", initial: "K", color: "#EF4444", text: "Third time this year same spot collapses. Quality of repair work is terrible.", likes: 78, timeAgo: "8h", isOfficial: false, isPinned: false, replies: [] },
  ],
  r2: [
    { id: "c11", userName: "Rohan G.", initial: "R", color: "#3B82F6", text: "My car engine got hydrolocked here last monsoon. Insurance did not cover it 😤", likes: 67, timeAgo: "3h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c12", userName: "BMC Ward Office", initial: "B", color: "#3B82F6", text: "Emergency pumps deployed. Drainage cleaning scheduled for tomorrow 6 AM.", likes: 112, timeAgo: "2h", isOfficial: true, isPinned: true, replies: [
      { id: "r3", userName: "Sneha D.", text: "Thank you for quick response! 🙏", likes: 15, timeAgo: "1h" },
    ] },
    { id: "c13", userName: "Pooja M.", initial: "P", color: "#EC4899", text: "Kids could not go to school today because of this. Happens every monsoon! 😢", likes: 45, timeAgo: "4h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c14", userName: "Vikram S.", initial: "V", color: "#F59E0B", text: "The garbage in drains is the root cause. Need regular cleaning before monsoon.", likes: 89, timeAgo: "4h", isOfficial: false, isPinned: false, replies: [] },
  ],
  r3: [
    { id: "c15", userName: "Sagar K.", initial: "S", color: "#22C55E", text: "I nearly got into an accident here yesterday. Chaos during evening rush hour.", likes: 23, timeAgo: "5h", isOfficial: false, isPinned: false, replies: [] },
    { id: "c16", userName: "Anita R.", initial: "A", color: "#8B5CF6", text: "Traffic police should at least station someone here temporarily.", likes: 34, timeAgo: "6h", isOfficial: false, isPinned: false, replies: [] },
  ],
  r5: [
    { id: "c17", userName: "Mumbai Police", initial: "MP", color: "#3B82F6", text: "Highway patrol alerted. Temporary barricades being set up. Use caution.", likes: 156, timeAgo: "30m", isOfficial: true, isPinned: true, replies: [
      { id: "r4", userName: "Anonymous", text: "About time! People are risking lives here.", likes: 34, timeAgo: "20m" },
    ] },
    { id: "c18", userName: "Manoj D.", initial: "M", color: "#EF4444", text: "I saw the accident last night. Horrifying. This needs immediate repair.", likes: 89, timeAgo: "1h", isOfficial: false, isPinned: false, replies: [] },
  ],
  r10: [
    { id: "c19", userName: "Thane MC", initial: "T", color: "#3B82F6", text: "Emergency team on site. Road closed for repairs. Expected completion: 72 hours.", likes: 234, timeAgo: "15m", isOfficial: true, isPinned: true, replies: [
      { id: "r5", userName: "Suresh K.", text: "72 hours?! This is a main road! Please expedite.", likes: 56, timeAgo: "10m" },
    ] },
    { id: "c20", userName: "Ganesh R.", initial: "G", color: "#F97316", text: "I could hear the road collapse from my apartment. Terrifying sound at 3 AM.", likes: 123, timeAgo: "25m", isOfficial: false, isPinned: false, replies: [] },
  ],
};

// ─── Stories ─────────────────────────────────────────────────────────────────

export const MOCK_STORIES: StoryItem[] = [
  { id: "s1", type: "new", label: "Report" },
  { id: "s2", type: "report", emoji: "🕳", location: "Andheri W", severity: "critical", reportId: "r1",
    thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=120&q=60" },
  { id: "s3", type: "report", emoji: "🌊", location: "Bandra", severity: "high", reportId: "r2",
    thumbnailUrl: "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=120&q=60" },
  { id: "s4", type: "report", emoji: "🚦", location: "Dadar", severity: "medium", reportId: "r3",
    thumbnailUrl: "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?auto=format&fit=crop&w=120&q=60" },
  { id: "s5", type: "report", emoji: "💥", location: "Kurla", severity: "critical", reportId: "r5",
    thumbnailUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?auto=format&fit=crop&w=120&q=60" },
  { id: "s6", type: "report", emoji: "🪨", location: "Borivali", severity: "low", reportId: "r4",
    thumbnailUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=120&q=60" },
  { id: "s7", type: "report", emoji: "🕳", location: "Pune", severity: "high", reportId: "r6",
    thumbnailUrl: "https://images.unsplash.com/photo-1560782205-4dd83ceb0270?auto=format&fit=crop&w=120&q=60" },
  { id: "s8", type: "report", emoji: "💧", location: "Nagpur", severity: "high", reportId: "r7",
    thumbnailUrl: "https://images.unsplash.com/photo-1601128533718-374ffcca299b?auto=format&fit=crop&w=120&q=60" },
];

// ─── Scope Options ────────────────────────────────────────────────────────────

export const SCOPE_OPTIONS: ScopeOption[] = [
  { key: "sub-district", icon: "📍", label: "My Sub-district", sublabel: "Andheri West", count: "247 reports" },
  { key: "district",     icon: "🏙", label: "My District",     sublabel: "Mumbai City",  count: "1.2K reports" },
  { key: "state",        icon: "🏛", label: "My State",        sublabel: "Maharashtra",  count: "8.4K reports" },
  { key: "national",     icon: "🇮🇳", label: "National",       sublabel: "All India",    count: "52K reports" },
];

// ─── Status Steps ─────────────────────────────────────────────────────────────

export const STATUS_STEPS = [
  "Submitted",
  "Verified",
  "Assigned",
  "In Progress",
  "Resolved",
] as const;

// ─── Severity Config ──────────────────────────────────────────────────────────

export const SEVERITY_COLORS: Record<string, string> = {
  low:      "#22C55E",
  medium:   "#F59E0B",
  high:     "#F97316",
  critical: "#EF4444",
};

export const SEVERITY_LABELS: Record<string, string> = {
  low:      "Low",
  medium:   "Medium",
  high:     "High",
  critical: "Critical",
};

// ─── Risk Score Colors (for UI badge rendering) ───────────────────────────────

export const RISK_SCORE_COLOR = (score: number): string => {
  if (score >= 85) return "#EF4444"; // Critical — red
  if (score >= 65) return "#F97316"; // High — orange
  if (score >= 45) return "#F59E0B"; // Medium — amber
  return "#22C55E";                  // Low — green
};

// ─── Media Renderer Helper (use in component) ─────────────────────────────────
//
//  if (item.mediaType === "image") {
//    return <img src={item.mediaUrl} className="w-full h-full object-cover" />
//  }
//
//  if (item.mediaType === "video") {
//    return (
//      <video
//        src={item.mediaUrl}
//        poster={item.thumbnailUrl}
//        autoPlay
//        muted
//        loop
//        playsInline
//        className="w-full h-full object-cover"
//      />
//    )
//  }

// ─── Extra mock data for community-roadDamage images ───────────────────────

const EXTRA_FEED_METADATA = [
  {
    id: "cr1",
    imageName: "122305545.webp",
    userName: "Aarav S.",
    userInitial: "A",
    userColor: "#EF4444",
    location: "Panvel Highway, Navi Mumbai",
    road: "NH-48 near Expressway exit",
    timeAgo: "10m ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "critical",
    title: "Dangerous deep pothole near Panvel Highway",
    description: "Huge pothole right after the highway exit. Cars are braking suddenly to avoid it, causing near-misses. Needs immediate filling.",
    riskScore: 89,
    trustScore: 92,
    verificationPercent: 95,
    authorityStatus: "Assigned — NHAI Navi Mumbai",
    verifiedCitizensCount: 18,
    status: "assigned",
    statusStep: 3,
    upvotes: 142,
    comments: 12,
    shares: 25,
    saves: 89,
    views: 1800,
    officialResponse: false,
    coordinates: { lat: 19.0024, lng: 73.1025 },
  },
  {
    id: "cr2",
    imageName: "125046762.webp",
    userName: "Ananya K.",
    userInitial: "A",
    userColor: "#3B82F6",
    location: "Sector 12, Kharghar",
    road: "Main Road near Shilp Chowk",
    timeAgo: "45m ago",
    hazardType: "flooding",
    hazardEmoji: "🌊",
    severity: "high",
    title: "Severe waterlogging near Sector 12",
    description: "Drainage is completely choked, causing rainwater to flood the entire street. Two-wheelers are getting stuck.",
    riskScore: 78,
    trustScore: 85,
    verificationPercent: 88,
    authorityStatus: "In Review — CIDCO",
    verifiedCitizensCount: 24,
    status: "verified",
    statusStep: 2,
    upvotes: 215,
    comments: 28,
    shares: 42,
    saves: 110,
    views: 3200,
    officialResponse: false,
    coordinates: { lat: 19.0345, lng: 73.0645 },
  },
  {
    id: "cr3",
    imageName: "4148.webp",
    userName: "Rohan M.",
    userInitial: "R",
    userColor: "#F59E0B",
    location: "Andheri East, Mumbai",
    road: "LBS Marg near Metro Pillar 45",
    timeAgo: "1h ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "critical",
    title: "Road surface collapse near Andheri",
    description: "A large section of the asphalt has collapsed. The area is extremely dangerous and poorly barricaded. Please avoid this lane.",
    riskScore: 92,
    trustScore: 89,
    verificationPercent: 91,
    authorityStatus: "In Progress — BMC Andheri",
    verifiedCitizensCount: 45,
    status: "in_progress",
    statusStep: 4,
    upvotes: 384,
    comments: 56,
    shares: 92,
    saves: 310,
    views: 6400,
    officialResponse: true,
    coordinates: { lat: 19.1158, lng: 72.8712 },
  },
  {
    id: "cr4",
    imageName: "80689_19_5_2025_19_35_46_1_PSX_20250519_192346.webp",
    userName: "Vikram T.",
    userInitial: "V",
    userColor: "#10B981",
    location: "JVLR, Powai",
    road: "Jogeshwari-Vikhroli Link Road near lake",
    timeAgo: "2h ago",
    hazardType: "accident",
    hazardEmoji: "💥",
    severity: "high",
    title: "Damaged divider causing accidents near Powai",
    description: "The concrete block of the central divider is broken and sticking out into the fast lane. Multiple cars hit it last night.",
    riskScore: 84,
    trustScore: 87,
    verificationPercent: 89,
    authorityStatus: "Assigned — MMRDA",
    verifiedCitizensCount: 31,
    status: "assigned",
    statusStep: 3,
    upvotes: 276,
    comments: 39,
    shares: 73,
    saves: 215,
    views: 4800,
    officialResponse: false,
    coordinates: { lat: 19.1245, lng: 72.9056 },
  },
  {
    id: "cr5",
    imageName: "ANI-20230709164644.webp",
    userName: "Priya N.",
    userInitial: "P",
    userColor: "#8B5CF6",
    location: "School Zone, Borivali",
    road: "Gorai Road near St. Francis School",
    timeAgo: "3h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "critical",
    title: "Large pothole near school zone",
    description: "Very deep pothole right in front of the school crossing. School buses and rickshaws are struggling to navigate safely.",
    riskScore: 95,
    trustScore: 94,
    verificationPercent: 98,
    authorityStatus: "Emergency — BMC Borivali Ward",
    verifiedCitizensCount: 78,
    status: "in_progress",
    statusStep: 4,
    upvotes: 541,
    comments: 84,
    shares: 142,
    saves: 420,
    views: 11000,
    officialResponse: true,
    coordinates: { lat: 19.2278, lng: 72.8342 },
  },
  {
    id: "cr6",
    imageName: "Atul-1.webp",
    userName: "Karthik D.",
    userInitial: "K",
    userColor: "#EC4899",
    location: "Railway Crossing, Dadar",
    road: "Senapati Bapat Marg",
    timeAgo: "5h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "medium",
    title: "Broken road near railway crossing",
    description: "Asphalt has completely washed away near the Dadar railway crossing tracks. Heavy traffic build-up due to slow-moving vehicles.",
    riskScore: 68,
    trustScore: 79,
    verificationPercent: 82,
    authorityStatus: "Pending — Central Railways & BMC",
    verifiedCitizensCount: 15,
    status: "submitted",
    statusStep: 1,
    upvotes: 112,
    comments: 14,
    shares: 19,
    saves: 83,
    views: 2400,
    officialResponse: false,
    coordinates: { lat: 19.0194, lng: 72.8428 },
  },
  {
    id: "cr7",
    imageName: "Ayodhya Rain_7.webp",
    userName: "Neha S.",
    userInitial: "N",
    userColor: "#06B6D4",
    location: "Underpass Road, Sion",
    road: "Sion-Dharavi Link Road",
    timeAgo: "6h ago",
    hazardType: "flooding",
    hazardEmoji: "🌊",
    severity: "high",
    title: "Flooded underpass blocking traffic near Sion",
    description: "Heavy monsoon water logging inside the underpass. Water is knee-deep. Pedestrians and auto rickshaws cannot pass through.",
    riskScore: 82,
    trustScore: 88,
    verificationPercent: 91,
    authorityStatus: "Pending — BMC Sion Division",
    verifiedCitizensCount: 25,
    status: "submitted",
    statusStep: 1,
    upvotes: 189,
    comments: 25,
    shares: 54,
    saves: 120,
    views: 3900,
    officialResponse: false,
    coordinates: { lat: 19.0384, lng: 72.8596 },
  },
  {
    id: "cr8",
    imageName: "Construction-debris-dumped-on-the-road-by-contract_1682940538780.webp",
    userName: "Sunil G.",
    userInitial: "S",
    userColor: "#F59E0B",
    location: "Bandra West, Mumbai",
    road: "Hill Road opposite National College",
    timeAgo: "7h ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "low",
    title: "Construction debris on Bandra Road blocking path",
    description: "Rubble and sand from nearby construction site dumped directly on the busy main road. Pedestrians forced into heavy traffic flow.",
    riskScore: 45,
    trustScore: 82,
    verificationPercent: 92,
    authorityStatus: "Resolved — BMC Bandra Ward",
    verifiedCitizensCount: 8,
    status: "resolved",
    statusStep: 5,
    upvotes: 94,
    comments: 8,
    shares: 12,
    saves: 43,
    views: 1500,
    officialResponse: false,
    coordinates: { lat: 19.0624, lng: 72.8345 },
  },
  {
    id: "cr9",
    imageName: "Cracks-on-Velachery.webp",
    userName: "Deepika V.",
    userInitial: "D",
    userColor: "#10B981",
    location: "Eastern Express Highway, Mulund",
    road: "Mulund Flyover Expansion Joint",
    timeAgo: "8h ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "high",
    title: "Deep cracks on flyover expansion joint",
    description: "Noticeable structure cracks on the concrete surface near the expansion joints. Requires engineering review before it worsens.",
    riskScore: 79,
    trustScore: 86,
    verificationPercent: 88,
    authorityStatus: "Assigned — MSRDC Mulund",
    verifiedCitizensCount: 22,
    status: "assigned",
    statusStep: 3,
    upvotes: 312,
    comments: 43,
    shares: 81,
    saves: 270,
    views: 5800,
    officialResponse: false,
    coordinates: { lat: 19.1724, lng: 72.9567 },
  },
  {
    id: "cr10",
    imageName: "LMFRR3XLX5ISVD432GFVURELEY.webp",
    userName: "Rajesh L.",
    userInitial: "R",
    userColor: "#EF4444",
    location: "Ghodbunder Road, Thane",
    road: "Near Waghbil Naka",
    timeAgo: "9h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "critical",
    title: "Major sinkhole on Ghodbunder Road",
    description: "A massive sinkhole has appeared suddenly after heavy rains, blocking two key lanes. Major safety risk at night.",
    riskScore: 97,
    trustScore: 92,
    verificationPercent: 96,
    authorityStatus: "In Progress — Thane MC",
    verifiedCitizensCount: 95,
    status: "in_progress",
    statusStep: 4,
    upvotes: 624,
    comments: 95,
    shares: 184,
    saves: 490,
    views: 15000,
    officialResponse: true,
    coordinates: { lat: 19.2456, lng: 72.9723 },
  },
  {
    id: "cr11",
    imageName: "Mumbai-Pothole.webp",
    userName: "Aditi H.",
    userInitial: "A",
    userColor: "#3B82F6",
    location: "Link Road, Santacruz",
    road: "Near Milan Subway Junction",
    timeAgo: "10h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "high",
    title: "Severe road hazard near Santacruz subway",
    description: "Cluster of deep potholes near the subway entrance. Auto rickshaws frequently lose balance here. Extremely risky for bikes.",
    riskScore: 82,
    trustScore: 84,
    verificationPercent: 86,
    authorityStatus: "Verified — BMC Santacruz",
    verifiedCitizensCount: 31,
    status: "verified",
    statusStep: 2,
    upvotes: 243,
    comments: 31,
    shares: 48,
    saves: 140,
    views: 4200,
    officialResponse: false,
    coordinates: { lat: 19.0834, lng: 72.8423 },
  },
  {
    id: "cr12",
    imageName: "PTI10-05-2025-000050A-0_1759649005485_1759649040639_1762683990454.webp",
    userName: "Vijay B.",
    userInitial: "V",
    userColor: "#8B5CF6",
    location: "Vaikunth Mehta Road, Vile Parle",
    road: "Near Cooper Hospital",
    timeAgo: "11h ago",
    hazardType: "flooding",
    hazardEmoji: "🌊",
    severity: "high",
    title: "Water clogging on SV Road near Hospital",
    description: "Monsoon floodwater has accumulated on the main lane outside the hospital gates. Slows down emergency ambulance access.",
    riskScore: 85,
    trustScore: 89,
    verificationPercent: 92,
    authorityStatus: "Assigned — Cooper Ward Office",
    verifiedCitizensCount: 49,
    status: "assigned",
    statusStep: 3,
    upvotes: 387,
    comments: 49,
    shares: 95,
    saves: 280,
    views: 6900,
    officialResponse: false,
    coordinates: { lat: 19.1089, lng: 72.8398 },
  },
  {
    id: "cr13",
    imageName: "Part-of-under-cGRUF8URDR.2.webp",
    userName: "Kiran J.",
    userInitial: "K",
    userColor: "#EC4899",
    location: "Sea Face, Worli",
    road: "Worli Sea Face Promenade",
    timeAgo: "12h ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "medium",
    title: "Collapsed footpath near Worli sea face",
    description: "Part of the sea face walkway has caved in due to tidal erosion. No proper warning tape or signs installed. Risk to evening walkers.",
    riskScore: 65,
    trustScore: 71,
    verificationPercent: 74,
    authorityStatus: "Pending — BMC G-South Ward",
    verifiedCitizensCount: 18,
    status: "submitted",
    statusStep: 1,
    upvotes: 154,
    comments: 18,
    shares: 24,
    saves: 95,
    views: 3100,
    officialResponse: false,
    coordinates: { lat: 19.0089, lng: 72.8156 },
  },
  {
    id: "cr14",
    imageName: "Perambur-mahole-Raghukumar.webp",
    userName: "Pooja C.",
    userInitial: "P",
    userColor: "#06B6D4",
    location: "Station Road, Kurla",
    road: "Near West Exit Junction",
    timeAgo: "13h ago",
    hazardType: "accident",
    hazardEmoji: "💥",
    severity: "critical",
    title: "Open manhole on busy Kurla Link Road",
    description: "Highly dangerous open sewer manhole in the middle of a very busy street. Pedestrians have placed dry branches to warn motorists.",
    riskScore: 96,
    trustScore: 91,
    verificationPercent: 95,
    authorityStatus: "In Progress — Kurla Drainage Dept",
    verifiedCitizensCount: 112,
    status: "in_progress",
    statusStep: 4,
    upvotes: 754,
    comments: 112,
    shares: 231,
    saves: 680,
    views: 18000,
    officialResponse: true,
    coordinates: { lat: 19.0723, lng: 72.8765 },
  },
  {
    id: "cr15",
    imageName: "Screenshot 2024-09-23 000138.webp",
    userName: "Siddharth W.",
    userInitial: "S",
    userColor: "#10B981",
    location: "Karve Road, Kothrud",
    road: "Near MIT College Junction",
    timeAgo: "14h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "medium",
    title: "Bad road conditions in Kothrud college zone",
    description: "Pothole patch that is causing scooter slips. Students traveling to college daily face extreme difficulties navigating this.",
    riskScore: 58,
    trustScore: 92,
    verificationPercent: 94,
    authorityStatus: "Resolved — Pune MC",
    verifiedCitizensCount: 11,
    status: "resolved",
    statusStep: 5,
    upvotes: 119,
    comments: 11,
    shares: 15,
    saves: 62,
    views: 2100,
    officialResponse: false,
    coordinates: { lat: 18.5089, lng: 73.8112 },
  },
  {
    id: "cr16",
    imageName: "Sinkhole.webp",
    userName: "Harish N.",
    userInitial: "H",
    userColor: "#EF4444",
    location: "School Zone, Borivali",
    road: "Link Road near IC Colony",
    timeAgo: "15h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "critical",
    title: "Dangerous sinkhole near school area",
    description: "A massive collapse of the sub-base layer under the asphalt. Road is hollow underneath. Immediate closure of this lane required.",
    riskScore: 94,
    trustScore: 89,
    verificationPercent: 91,
    authorityStatus: "In Progress — BMC Road Dept",
    verifiedCitizensCount: 62,
    status: "in_progress",
    statusStep: 4,
    upvotes: 498,
    comments: 62,
    shares: 112,
    saves: 340,
    views: 9200,
    officialResponse: true,
    coordinates: { lat: 19.2423, lng: 72.8489 },
  },
  {
    id: "cr17",
    imageName: "Tree_fall_02.webp",
    userName: "Shruti A.",
    userInitial: "S",
    userColor: "#3B82F6",
    location: "Palm Beach Road, Sanpada",
    road: "Near Moraj Circle",
    timeAgo: "16h ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "high",
    title: "Fallen tree blocking two lanes in Navi Mumbai",
    description: "Heavy storm caused a large tree branch to fall across the highway lanes. Traffic is backing up. Rescue/cutting crew required.",
    riskScore: 82,
    trustScore: 94,
    verificationPercent: 96,
    authorityStatus: "Resolved — NMMC Garden Dept",
    verifiedCitizensCount: 34,
    status: "resolved",
    statusStep: 5,
    upvotes: 289,
    comments: 34,
    shares: 62,
    saves: 190,
    views: 5100,
    officialResponse: false,
    coordinates: { lat: 19.0123, lng: 73.0189 },
  },
  {
    id: "cr18",
    imageName: "anaath-road_8c2bb80a-58ee-11e7-b50f-ad66c5ec5579.webp",
    userName: "Manish Y.",
    userInitial: "M",
    userColor: "#F59E0B",
    location: "Western Express Highway, Goregaon",
    road: "Aarey Colony Road Entry",
    timeAgo: "17h ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "medium",
    title: "Unpaved mud road causing skid hazards",
    description: "Uncompleted road construction left open. Dirt and gravel have turned into slick mud after light drizzle, causing two-wheelers to slip.",
    riskScore: 61,
    trustScore: 78,
    verificationPercent: 81,
    authorityStatus: "Assigned — PWD Road Division",
    verifiedCitizensCount: 21,
    status: "assigned",
    statusStep: 3,
    upvotes: 176,
    comments: 21,
    shares: 38,
    saves: 112,
    views: 3400,
    officialResponse: false,
    coordinates: { lat: 19.1645, lng: 72.8598 },
  },
  {
    id: "cr19",
    imageName: "atyuug.webp",
    userName: "Kavita O.",
    userInitial: "K",
    userColor: "#8B5CF6",
    location: "Juhu Tara Road, Juhu",
    road: "Near Juhu Beach main entrance",
    timeAgo: "18h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "high",
    title: "Severe pothole patch near Vashi / Juhu",
    description: "Deep potholes filled with dirty water. Hard to judge depth. Car bumpers scraping continuously. Traffic moving at snail's pace.",
    riskScore: 84,
    trustScore: 81,
    verificationPercent: 85,
    authorityStatus: "Verified — BMC K-West",
    verifiedCitizensCount: 45,
    status: "verified",
    statusStep: 2,
    upvotes: 321,
    comments: 45,
    shares: 89,
    saves: 220,
    views: 6100,
    officialResponse: false,
    coordinates: { lat: 19.0984, lng: 72.8273 },
  },
  {
    id: "cr20",
    imageName: "down-to-earth_import_library_large_2019-07-05_0.83462400_1562316663_debris.webp",
    userName: "Ravi F.",
    userInitial: "R",
    userColor: "#EC4899",
    location: "Pune-Mumbai Expressway, Khalapur",
    road: "Near Bhor Ghat Section",
    timeAgo: "19h ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "critical",
    title: "Landslide debris on Pune-Mumbai Expressway",
    description: "Rock and soil collapse has spilled over into the left two lanes. Extremely dangerous on curves. Highway patrol on scene directing traffic.",
    riskScore: 95,
    trustScore: 92,
    verificationPercent: 96,
    authorityStatus: "In Progress — MSRDC Emergency Crew",
    verifiedCitizensCount: 142,
    status: "in_progress",
    statusStep: 4,
    upvotes: 890,
    comments: 142,
    shares: 310,
    saves: 740,
    views: 21000,
    officialResponse: true,
    coordinates: { lat: 18.7765, lng: 73.3456 },
  },
  {
    id: "cr21",
    imageName: "gandacherra-residents-continue-to-suffer-due-to-poor-road-conditions.webp",
    userName: "Shweta E.",
    userInitial: "S",
    userColor: "#06B6D4",
    location: "MG Road, Pune",
    road: "Camp Area Market Street",
    timeAgo: "20h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "medium",
    title: "Broken road connection in market area",
    description: "Large potholes and mud holes in the middle of the local market road. High pedestrian area makes it a major trip hazard.",
    riskScore: 54,
    trustScore: 72,
    verificationPercent: 75,
    authorityStatus: "Pending — Pune MC Ward 4",
    verifiedCitizensCount: 16,
    status: "submitted",
    statusStep: 1,
    upvotes: 134,
    comments: 16,
    shares: 23,
    saves: 78,
    views: 2800,
    officialResponse: false,
    coordinates: { lat: 18.5145, lng: 73.8789 },
  },
  {
    id: "cr22",
    imageName: "high.webp",
    userName: "Arjun U.",
    userInitial: "A",
    userColor: "#10B981",
    location: "NH-48, Panvel",
    road: "Near Kalamboli circle",
    timeAgo: "21h ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "high",
    title: "Highway road erosion near Panvel bypass",
    description: "Asphalt layers completely worn down to sub-base. Deep ruts forming that pull vehicle steering wheel. Dangerous for trucks.",
    riskScore: 81,
    trustScore: 83,
    verificationPercent: 85,
    authorityStatus: "Assigned — NHAI Road Maintenance",
    verifiedCitizensCount: 39,
    status: "assigned",
    statusStep: 3,
    upvotes: 304,
    comments: 39,
    shares: 67,
    saves: 185,
    views: 5300,
    officialResponse: false,
    coordinates: { lat: 19.0234, lng: 73.0945 },
  },
  {
    id: "cr23",
    imageName: "hvhyvg.webp",
    userName: "Meera Z.",
    userInitial: "M",
    userColor: "#EF4444",
    location: "Station Road, Borivali",
    road: "Borivali Station West Exit",
    timeAgo: "22h ago",
    hazardType: "accident",
    hazardEmoji: "💥",
    severity: "medium",
    title: "Damaged speed breaker near Borivali station",
    description: "Broken speed breaker blocks with steel bolts protruding. Damaging tires of cars and buses passing over it.",
    riskScore: 59,
    trustScore: 91,
    verificationPercent: 93,
    authorityStatus: "Resolved — BMC Borivali Ward",
    verifiedCitizensCount: 21,
    status: "resolved",
    statusStep: 5,
    upvotes: 145,
    comments: 15,
    shares: 21,
    saves: 79,
    views: 2900,
    officialResponse: false,
    coordinates: { lat: 19.2294, lng: 72.8564 },
  },
  {
    id: "cr24",
    imageName: "im.webp",
    userName: "Dev Q.",
    userInitial: "D",
    userColor: "#3B82F6",
    location: "Western Express Highway, Bandra",
    road: "Near Kalanagar Junction",
    timeAgo: "23h ago",
    hazardType: "accident",
    hazardEmoji: "💥",
    severity: "critical",
    title: "Missing drainage cover on Western Express Highway",
    description: "Open drainage pit right on the shoulder lane of WEH. Lethal for motorbikes and flat tires if hit at highway speeds.",
    riskScore: 97,
    trustScore: 93,
    verificationPercent: 95,
    authorityStatus: "In Progress — WEH PWD Maintenance",
    verifiedCitizensCount: 92,
    status: "in_progress",
    statusStep: 4,
    upvotes: 689,
    comments: 92,
    shares: 215,
    saves: 540,
    views: 16000,
    officialResponse: true,
    coordinates: { lat: 19.0623, lng: 72.8489 },
  },
  {
    id: "cr25",
    imageName: "ima.webp",
    userName: "Divya K.",
    userInitial: "D",
    userColor: "#F59E0B",
    location: "Station Road, Kurla",
    road: "LBS Marg outside Phoenix Marketcity",
    timeAgo: "1d ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "high",
    title: "Large crater on road near Kurla Station",
    description: "Huge crater that collects muddy water. Vehicles have to merge into a single lane to avoid it, causing extreme jams.",
    riskScore: 82,
    trustScore: 84,
    verificationPercent: 86,
    authorityStatus: "Verified — BMC Kurla Office",
    verifiedCitizensCount: 48,
    status: "verified",
    statusStep: 2,
    upvotes: 378,
    comments: 48,
    shares: 94,
    saves: 240,
    views: 7200,
    officialResponse: false,
    coordinates: { lat: 19.0784, lng: 72.8876 },
  },
  {
    id: "cr26",
    imageName: "images.webp",
    userName: "Sameer G.",
    userInitial: "S",
    userColor: "#8B5CF6",
    location: "Pokhran Road, Thane",
    road: "Near Upvan Lake entrance",
    timeAgo: "1d ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "medium",
    title: "Damaged road surface near Thane Upvan area",
    description: "Pavement is completely cracked and disintegrating. Creates heavy dust and bumpy rides. Highly annoying for residents.",
    riskScore: 59,
    trustScore: 91,
    verificationPercent: 93,
    authorityStatus: "Resolved — Thane MC Ward 2",
    verifiedCitizensCount: 21,
    status: "resolved",
    statusStep: 5,
    upvotes: 189,
    comments: 21,
    shares: 34,
    saves: 110,
    views: 3900,
    officialResponse: false,
    coordinates: { lat: 19.2194, lng: 72.9645 },
  },
  {
    id: "cr27",
    imageName: "images_1596688243697_WhatsApp_Image_2020_08_06_at_07.41.32.webp",
    userName: "Preeti T.",
    userInitial: "P",
    userColor: "#EC4899",
    location: "Chembur Colony, Chembur",
    road: "RC Marg near Monorail Station",
    timeAgo: "2d ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "low",
    title: "Puddles and potholes near Chembur Monorail",
    description: "Multiple shallow potholes filled with stagnant water. Mosquito breeding ground and causing splash damage to pedestrians.",
    riskScore: 34,
    trustScore: 71,
    verificationPercent: 73,
    authorityStatus: "Pending — BMC M-West Ward",
    verifiedCitizensCount: 8,
    status: "submitted",
    statusStep: 1,
    upvotes: 78,
    comments: 8,
    shares: 11,
    saves: 34,
    views: 1200,
    officialResponse: false,
    coordinates: { lat: 19.0434, lng: 72.8943 },
  },
  {
    id: "cr28",
    imageName: "imdf.webp",
    userName: "Ashish B.",
    userInitial: "A",
    userColor: "#06B6D4",
    location: "Mulund East, Mumbai",
    road: "Navghar Road near school",
    timeAgo: "2d ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "medium",
    title: "Road cracks causing bike slips near Mulund",
    description: "Longitudinal cracks in the road. Scooter tires get trapped in the grooves, causing riders to lose control. Repair required.",
    riskScore: 62,
    trustScore: 78,
    verificationPercent: 81,
    authorityStatus: "Assigned — BMC Mulund Ward",
    verifiedCitizensCount: 18,
    status: "assigned",
    statusStep: 3,
    upvotes: 145,
    comments: 18,
    shares: 27,
    saves: 90,
    views: 2900,
    officialResponse: false,
    coordinates: { lat: 19.1784, lng: 72.9723 },
  },
  {
    id: "cr29",
    imageName: "mangroves-hindustan-construction-majiwada-wednesday-november-gangurde_117f9b14-ed97-11e8-b312-d5ded9c11306.webp",
    userName: "Nisha R.",
    userInitial: "N",
    userColor: "#10B981",
    location: "Majiwada Junction, Thane",
    road: "Eastern Express Highway bypass",
    timeAgo: "3d ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "high",
    title: "Blocked service lane near Majiwada circle",
    description: "Unused construction machinery and barriers blocking the service road entrance. Causes highway traffic to merge abruptly.",
    riskScore: 76,
    trustScore: 84,
    verificationPercent: 86,
    authorityStatus: "Verified — TMC Road Dept",
    verifiedCitizensCount: 37,
    status: "verified",
    statusStep: 2,
    upvotes: 298,
    comments: 37,
    shares: 72,
    saves: 180,
    views: 5400,
    officialResponse: false,
    coordinates: { lat: 19.2156, lng: 72.9834 },
  },
  {
    id: "cr30",
    imageName: "national-highway-44-153327989-1x1.webp",
    userName: "Gautam V.",
    userInitial: "G",
    userColor: "#EF4444",
    location: "NH-44 Highway, Nagpur",
    road: "Nagpur-Jabalpur Highway stretch",
    timeAgo: "3d ago",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "critical",
    title: "Huge crater on NH-44 highway near Nagpur",
    description: "Very deep and wide pothole in the center of the high-speed highway. Extremely dangerous at night with no overhead illumination.",
    riskScore: 94,
    trustScore: 91,
    verificationPercent: 93,
    authorityStatus: "In Progress — NHAI Nagpur Div",
    verifiedCitizensCount: 69,
    status: "in_progress",
    statusStep: 4,
    upvotes: 512,
    comments: 69,
    shares: 134,
    saves: 310,
    views: 8900,
    officialResponse: true,
    coordinates: { lat: 21.2145, lng: 79.1234 },
  },
  {
    id: "cr31",
    imageName: "road.webp",
    userName: "Tanvi S.",
    userInitial: "T",
    userColor: "#3B82F6",
    location: "JVLR, Kanjurmarg",
    road: "Near Kanjurmarg Flyover entrance",
    timeAgo: "4d ago",
    hazardType: "debris",
    hazardEmoji: "🪨",
    severity: "medium",
    title: "Deteriorated asphalt on JVLR causing heavy dust",
    description: "Upper asphalt binder has eroded, exposing rough aggregates. Vehicles kick up huge clouds of dust, blocking visibility.",
    riskScore: 64,
    trustScore: 82,
    verificationPercent: 84,
    authorityStatus: "Resolved — MMRDA Maintenance",
    verifiedCitizensCount: 24,
    status: "resolved",
    statusStep: 5,
    upvotes: 167,
    comments: 24,
    shares: 38,
    saves: 110,
    views: 3400,
    officialResponse: false,
    coordinates: { lat: 19.1234, lng: 72.9345 },
  },
];

const EXTRA_FEED_ITEMS: ReportFeedItem[] = EXTRA_FEED_METADATA.map((item) => ({
  id: item.id,
  userName: item.userName,
  userInitial: item.userInitial,
  userColor: item.userColor,
  isAnonymous: false,
  isVerified: true,
  isFollowing: false,
  location: item.location,
  road: item.road,
  timeAgo: item.timeAgo,
  hazardType: item.hazardType,
  hazardEmoji: item.hazardEmoji,
  severity: item.severity as any,
  title: item.title,
  description: item.description,
  mediaType: "image",
  mediaUrl: `/images/community-roadDamage/${item.imageName}`,
  thumbnailUrl: `/images/community-roadDamage/${item.imageName}`,
  riskScore: item.riskScore,
  trustScore: item.trustScore,
  verificationPercent: item.verificationPercent,
  authorityStatus: item.authorityStatus,
  verifiedCitizensCount: item.verifiedCitizensCount,
  status: item.status as any,
  statusStep: item.statusStep,
  upvotes: item.upvotes,
  hasUpvoted: false,
  comments: item.comments,
  shares: item.shares,
  saves: item.saves,
  views: item.views,
  isSaved: false,
  officialResponse: item.officialResponse,
  coordinates: item.coordinates,
}));

export const MOCK_FEED: ReportFeedItem[] = [
  ...ORIGINAL_MOCK_FEED,
  ...EXTRA_FEED_ITEMS,
];

const EXTRA_COMMENTS = Object.fromEntries(
  EXTRA_FEED_METADATA.map((item) => [
    item.id,
    [
      {
        id: `c_${item.id}_1`,
        userName: "Local Commuter",
        initial: "L",
        color: "#3B82F6",
        text: `Agreed, this ${item.hazardType} is a major issue at ${item.location}. Hope it gets resolved soon.`,
        likes: Math.floor(Math.random() * 20) + 1,
        timeAgo: "2h",
        isOfficial: false,
        isPinned: false,
        replies: [],
      },
    ],
  ])
);

export const MOCK_COMMENTS: Record<string, CommentItem[]> = {
  ...ORIGINAL_MOCK_COMMENTS,
  ...EXTRA_COMMENTS,
};