import type { MyReport, UserStats } from "./types";

export const MOCK_MY_REPORTS: MyReport[] = [
  {
    id: "rpt-001",
    reportId: "RPT-2026-00412",
    title: "Large pothole causing accidents near Andheri Station flyover",
    description:
      "Pothole 2ft wide, 8 inches deep on SV Road. Two bikes fell this week. Municipality unresponsive for 3 weeks.",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "critical",
    status: "in_progress",
    statusStep: 4,
    location: {
      name: "Andheri West, Mumbai",
      road: "SV Road near Andheri Flyover",
      subdistrict: "Andheri West",
      district: "Mumbai City",
      state: "Maharashtra",
      lat: 19.1136,
      lng: 72.8697,
      gps: "19.1136° N, 72.8697° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=85",
    photoCount: 2,
    upvotes: 247,
    hasUpvoted: true,
    comments: 43,
    views: 1240,
    communityVerified: true,
    verificationCount: 12,
    isNotifying: true,
    createdAt: "2026-06-06T10:30:00Z",
    lastUpdatedAt: "2026-06-07T09:00:00Z",
    lastUpdatedBy: "BMC Mumbai",
    assignedTo: "Mumbai PWD Zone 3",
    expectedResolution: "2026-06-09",
    referenceId: "BMC-2026-4821",
    officialResponse: {
      author: "BMC Mumbai",
      isVerifiedAuthority: true,
      text: "We have logged this complaint (Ref: BMC-2026-4821). Repair team assigned, ETA 48 hours.",
      likes: 89,
      createdAt: "2026-06-07T08:00:00Z",
    },
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-06-06T10:30:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "Community", actorType: "community", note: "Verified by 12 community members.", date: "2026-06-06T11:00:00Z", completed: true },
      { step: "assigned", label: "Assigned", actor: "System", actorType: "system", note: "Auto-assigned to Mumbai PWD Zone 3.", date: "2026-06-07T08:00:00Z", completed: true },
      { step: "in_progress", label: "In Progress", actor: "BMC Mumbai", actorType: "authority", note: "Repair team dispatched to location.", date: "2026-06-07T09:00:00Z", completed: true },
      { step: "resolved", label: "Resolved", actor: "Mumbai PWD", actorType: "authority", note: "Pending resolution.", date: null, completed: false },
    ],
  },
  {
    id: "rpt-002",
    reportId: "RPT-2026-00398",
    title: "Severe waterlogging blocking entire road near Bandra station",
    description:
      "Water level 2ft high after last night rain. Vehicles stuck, pedestrians wading. Drainage blocked by garbage.",
    hazardType: "flooding",
    hazardEmoji: "🌊",
    severity: "high",
    status: "verified",
    statusStep: 2,
    location: {
      name: "Bandra West, Mumbai",
      road: "Hill Road near Bandra Station",
      subdistrict: "Bandra West",
      district: "Mumbai Suburban",
      state: "Maharashtra",
      lat: 19.0544,
      lng: 72.8401,
      gps: "19.0544° N, 72.8401° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=85",
    photoCount: 3,
    upvotes: 189,
    hasUpvoted: false,
    comments: 31,
    views: 890,
    communityVerified: true,
    verificationCount: 8,
    isNotifying: false,
    createdAt: "2026-06-05T14:20:00Z",
    lastUpdatedAt: "2026-06-05T15:00:00Z",
    lastUpdatedBy: "Community",
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-06-05T14:20:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "Community", actorType: "community", note: "Verified by 8 community members.", date: "2026-06-05T15:00:00Z", completed: true },
      { step: "assigned", label: "Assigned", actor: "", actorType: "system", note: "Awaiting authority assignment.", date: null, completed: false },
      { step: "in_progress", label: "In Progress", actor: "", actorType: "authority", note: "", date: null, completed: false },
      { step: "resolved", label: "Resolved", actor: "", actorType: "authority", note: "", date: null, completed: false },
    ],
  },
  {
    id: "rpt-003",
    reportId: "RPT-2026-00345",
    title: "Broken traffic signal at Dadar junction causing chaos",
    description:
      "Signal non-functional since 3 days. Near-miss accidents daily. Traffic police absent most of the time.",
    hazardType: "signal",
    hazardEmoji: "🚦",
    severity: "medium",
    status: "resolved",
    statusStep: 5,
    location: {
      name: "Dadar West, Mumbai",
      road: "Senapati Bapat Marg",
      subdistrict: "Dadar",
      district: "Mumbai City",
      state: "Maharashtra",
      lat: 19.0178,
      lng: 72.8478,
      gps: "19.0178° N, 72.8478° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1504222490345-c075b6008014?auto=format&fit=crop&w=800&q=85",
    photoCount: 1,
    upvotes: 134,
    hasUpvoted: true,
    comments: 22,
    views: 670,
    communityVerified: true,
    verificationCount: 15,
    isNotifying: true,
    createdAt: "2026-06-01T08:00:00Z",
    lastUpdatedAt: "2026-06-04T14:30:00Z",
    lastUpdatedBy: "Mumbai Traffic Police",
    assignedTo: "Mumbai Traffic Police",
    expectedResolution: "2026-06-04",
    referenceId: "MTP-2026-1122",
    officialResponse: {
      author: "Mumbai Traffic Police",
      isVerifiedAuthority: true,
      text: "Signal repaired and operational. Thank you for reporting.",
      likes: 45,
      createdAt: "2026-06-04T14:30:00Z",
    },
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-06-01T08:00:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "Community", actorType: "community", note: "Verified by 15 community members.", date: "2026-06-01T09:30:00Z", completed: true },
      { step: "assigned", label: "Assigned", actor: "System", actorType: "system", note: "Auto-assigned to Mumbai Traffic Police.", date: "2026-06-02T10:00:00Z", completed: true },
      { step: "in_progress", label: "In Progress", actor: "Mumbai Traffic Police", actorType: "authority", note: "Technician dispatched for signal repair.", date: "2026-06-03T11:00:00Z", completed: true },
      { step: "resolved", label: "Resolved", actor: "Mumbai Traffic Police", actorType: "authority", note: "Signal repaired and operational.", date: "2026-06-04T14:30:00Z", completed: true },
    ],
  },
  {
    id: "rpt-004",
    reportId: "RPT-2026-00450",
    title: "Fallen tree debris blocking half the road in Borivali",
    description:
      "Large tree branch fallen after storm. Blocking left lane. No authority has responded yet.",
    hazardType: "debris",
    hazardEmoji: "🌳",
    severity: "low",
    status: "submitted",
    statusStep: 1,
    location: {
      name: "Borivali West, Mumbai",
      road: "S.V. Road near Borivali Station",
      subdistrict: "Borivali",
      district: "Mumbai Suburban",
      state: "Maharashtra",
      lat: 19.2288,
      lng: 72.8544,
      gps: "19.2288° N, 72.8544° E",
    },
    hasPhoto: false,
    photoCount: 0,
    upvotes: 23,
    hasUpvoted: false,
    comments: 5,
    views: 120,
    communityVerified: false,
    verificationCount: 0,
    isNotifying: false,
    createdAt: "2026-06-07T06:00:00Z",
    lastUpdatedAt: "2026-06-07T06:00:00Z",
    lastUpdatedBy: "Rahul M.",
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-06-07T06:00:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "", actorType: "community", note: "Awaiting community verification.", date: null, completed: false },
      { step: "assigned", label: "Assigned", actor: "", actorType: "system", note: "", date: null, completed: false },
      { step: "in_progress", label: "In Progress", actor: "", actorType: "authority", note: "", date: null, completed: false },
      { step: "resolved", label: "Resolved", actor: "", actorType: "authority", note: "", date: null, completed: false },
    ],
  },
  {
    id: "rpt-005",
    reportId: "RPT-2026-00389",
    title: "Dangerous accident-prone curve with no signage on Eastern Express",
    description:
      "Sharp curve without warning signs. 4 accidents in last month. Need reflectors and speed breakers urgently.",
    hazardType: "accident",
    hazardEmoji: "⚠️",
    severity: "critical",
    status: "assigned",
    statusStep: 3,
    location: {
      name: "Kurla West, Mumbai",
      road: "Eastern Express Highway",
      subdistrict: "Kurla",
      district: "Mumbai Suburban",
      state: "Maharashtra",
      lat: 19.0726,
      lng: 72.8794,
      gps: "19.0726° N, 72.8794° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1590004987778-bece5c9adab6?auto=format&fit=crop&w=800&q=85",
    photoCount: 2,
    upvotes: 312,
    hasUpvoted: true,
    comments: 56,
    views: 2100,
    communityVerified: true,
    verificationCount: 20,
    isNotifying: true,
    isAnonymous: true,
    createdAt: "2026-06-03T16:00:00Z",
    lastUpdatedAt: "2026-06-06T10:00:00Z",
    lastUpdatedBy: "NHAI",
    assignedTo: "NHAI Mumbai Division",
    expectedResolution: "2026-06-12",
    referenceId: "NHAI-2026-0098",
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Anonymous", actorType: "citizen", note: "Report submitted anonymously.", date: "2026-06-03T16:00:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "Community", actorType: "community", note: "Verified by 20 community members.", date: "2026-06-04T09:00:00Z", completed: true },
      { step: "assigned", label: "Assigned", actor: "System", actorType: "system", note: "Auto-assigned to NHAI Mumbai Division.", date: "2026-06-06T10:00:00Z", completed: true },
      { step: "in_progress", label: "In Progress", actor: "", actorType: "authority", note: "Awaiting authority action.", date: null, completed: false },
      { step: "resolved", label: "Resolved", actor: "", actorType: "authority", note: "", date: null, completed: false },
    ],
  },
  {
    id: "rpt-006",
    reportId: "RPT-2026-00290",
    title: "Multiple potholes on Pune-Solapur highway stretch",
    description:
      "Series of potholes over 500m stretch. Several tyre punctures reported. Heavy truck traffic worsening conditions.",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "high",
    status: "resolved",
    statusStep: 5,
    location: {
      name: "Hadapsar, Pune",
      road: "Pune-Solapur Highway NH-65",
      subdistrict: "Hadapsar",
      district: "Pune",
      state: "Maharashtra",
      lat: 18.5018,
      lng: 73.9441,
      gps: "18.5018° N, 73.9441° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1601001815894-4bb6ce59aa1b?auto=format&fit=crop&w=800&q=85",
    photoCount: 4,
    upvotes: 98,
    hasUpvoted: false,
    comments: 19,
    views: 540,
    communityVerified: true,
    verificationCount: 6,
    isNotifying: false,
    createdAt: "2026-05-20T12:00:00Z",
    lastUpdatedAt: "2026-05-28T16:00:00Z",
    lastUpdatedBy: "Pune Municipal Corp",
    assignedTo: "Pune PWD",
    referenceId: "PMC-2026-3321",
    officialResponse: {
      author: "Pune Municipal Corp",
      isVerifiedAuthority: true,
      text: "Road resurfacing completed on the reported stretch. Please verify.",
      likes: 34,
      createdAt: "2026-05-28T16:00:00Z",
    },
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-05-20T12:00:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "Community", actorType: "community", note: "Verified by 6 community members.", date: "2026-05-20T14:00:00Z", completed: true },
      { step: "assigned", label: "Assigned", actor: "System", actorType: "system", note: "Auto-assigned to Pune PWD.", date: "2026-05-21T09:00:00Z", completed: true },
      { step: "in_progress", label: "In Progress", actor: "Pune Municipal Corp", actorType: "authority", note: "Road resurfacing work started.", date: "2026-05-25T08:00:00Z", completed: true },
      { step: "resolved", label: "Resolved", actor: "Pune Municipal Corp", actorType: "authority", note: "Road resurfacing completed.", date: "2026-05-28T16:00:00Z", completed: true },
    ],
  },
  {
    id: "rpt-007",
    reportId: "RPT-2026-00367",
    title: "Persistent waterlogging at Nagpur railway underpass",
    description:
      "Underpass floods with every rain. Water stays for days. No pumping infrastructure. Vehicles get stuck regularly.",
    hazardType: "flooding",
    hazardEmoji: "🌊",
    severity: "high",
    status: "in_progress",
    statusStep: 4,
    location: {
      name: "Sitabuldi, Nagpur",
      road: "Railway Station Underpass",
      subdistrict: "Sitabuldi",
      district: "Nagpur",
      state: "Maharashtra",
      lat: 21.1458,
      lng: 79.0882,
      gps: "21.1458° N, 79.0882° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1559060017-445fb9722f2a?auto=format&fit=crop&w=800&q=85",
    photoCount: 2,
    upvotes: 156,
    hasUpvoted: true,
    comments: 28,
    views: 780,
    communityVerified: true,
    verificationCount: 10,
    isNotifying: true,
    createdAt: "2026-05-28T07:00:00Z",
    lastUpdatedAt: "2026-06-05T11:00:00Z",
    lastUpdatedBy: "NMC Nagpur",
    assignedTo: "NMC Drainage Dept",
    expectedResolution: "2026-06-15",
    referenceId: "NMC-2026-0789",
    officialResponse: {
      author: "NMC Nagpur",
      isVerifiedAuthority: true,
      text: "Pumping equipment being installed. Permanent drainage solution under design.",
      likes: 23,
      createdAt: "2026-06-05T11:00:00Z",
    },
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-05-28T07:00:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "Community", actorType: "community", note: "Verified by 10 community members.", date: "2026-05-28T09:00:00Z", completed: true },
      { step: "assigned", label: "Assigned", actor: "System", actorType: "system", note: "Auto-assigned to NMC Drainage Dept.", date: "2026-05-30T10:00:00Z", completed: true },
      { step: "in_progress", label: "In Progress", actor: "NMC Nagpur", actorType: "authority", note: "Pumping equipment being installed.", date: "2026-06-05T11:00:00Z", completed: true },
      { step: "resolved", label: "Resolved", actor: "", actorType: "authority", note: "Pending completion.", date: null, completed: false },
    ],
  },
  {
    id: "rpt-008",
    reportId: "RPT-2026-00321",
    title: "Broken highway guardrail on NH-48 after truck collision",
    description:
      "50m of guardrail destroyed after truck accident. Cliff edge exposed. Extremely dangerous at night.",
    hazardType: "debris",
    hazardEmoji: "🛡️",
    severity: "critical",
    status: "rejected",
    statusStep: 2,
    location: {
      name: "Kasara Ghat, NH-48",
      road: "Mumbai-Nashik Highway NH-48",
      subdistrict: "Kasara",
      district: "Thane",
      state: "Maharashtra",
      lat: 19.6331,
      lng: 73.4747,
      gps: "19.6331° N, 73.4747° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=800&q=85",
    photoCount: 3,
    upvotes: 67,
    hasUpvoted: false,
    comments: 12,
    views: 340,
    communityVerified: false,
    verificationCount: 2,
    isNotifying: false,
    rejectionReason: "Duplicate report. Already being handled under RPT-2026-00298.",
    createdAt: "2026-05-25T18:00:00Z",
    lastUpdatedAt: "2026-05-26T09:00:00Z",
    lastUpdatedBy: "System",
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-05-25T18:00:00Z", completed: true },
      { step: "rejected", label: "Rejected", actor: "System", actorType: "system", note: "Duplicate report. Already being handled under RPT-2026-00298.", date: "2026-05-26T09:00:00Z", completed: true },
    ],
  },
  {
    id: "rpt-009",
    reportId: "RPT-2026-00430",
    title: "Street light completely out on main road near Andheri East metro",
    description:
      "Row of 4 street lights non-functional for a week. Area pitch dark at night. Safety concern for women.",
    hazardType: "signal",
    hazardEmoji: "💡",
    severity: "low",
    status: "verified",
    statusStep: 2,
    location: {
      name: "Andheri East, Mumbai",
      road: "Marol Maroshi Road",
      subdistrict: "Andheri East",
      district: "Mumbai Suburban",
      state: "Maharashtra",
      lat: 19.1094,
      lng: 72.8803,
      gps: "19.1094° N, 72.8803° E",
    },
    hasPhoto: false,
    photoCount: 0,
    upvotes: 45,
    hasUpvoted: false,
    comments: 8,
    views: 210,
    communityVerified: true,
    verificationCount: 5,
    isNotifying: false,
    createdAt: "2026-06-06T20:00:00Z",
    lastUpdatedAt: "2026-06-06T22:00:00Z",
    lastUpdatedBy: "Community",
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-06-06T20:00:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "Community", actorType: "community", note: "Verified by 5 community members.", date: "2026-06-06T22:00:00Z", completed: true },
      { step: "assigned", label: "Assigned", actor: "", actorType: "system", note: "Awaiting assignment.", date: null, completed: false },
      { step: "in_progress", label: "In Progress", actor: "", actorType: "authority", note: "", date: null, completed: false },
      { step: "resolved", label: "Resolved", actor: "", actorType: "authority", note: "", date: null, completed: false },
    ],
  },
  {
    id: "rpt-010",
    reportId: "RPT-2026-00378",
    title: "Road cave-in near Thane creek bridge approach road",
    description:
      "Road surface caved in 3ft deep, 5ft wide. Barricades placed but insufficient. Heavy traffic area.",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "critical",
    status: "in_progress",
    statusStep: 4,
    location: {
      name: "Thane West",
      road: "Ghodbunder Road near Creek Bridge",
      subdistrict: "Thane West",
      district: "Thane",
      state: "Maharashtra",
      lat: 19.2183,
      lng: 72.9781,
      gps: "19.2183° N, 72.9781° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1621600411688-4f25d62be4ce?auto=format&fit=crop&w=800&q=85",
    photoCount: 3,
    upvotes: 201,
    hasUpvoted: true,
    comments: 38,
    views: 1560,
    communityVerified: true,
    verificationCount: 18,
    isNotifying: true,
    createdAt: "2026-05-30T09:00:00Z",
    lastUpdatedAt: "2026-06-06T14:00:00Z",
    lastUpdatedBy: "TMC Thane",
    assignedTo: "TMC Road Dept",
    expectedResolution: "2026-06-10",
    referenceId: "TMC-2026-0456",
    officialResponse: {
      author: "TMC Thane",
      isVerifiedAuthority: true,
      text: "Emergency repair initiated. Full road restoration expected within 5 days.",
      likes: 56,
      createdAt: "2026-06-06T14:00:00Z",
    },
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-05-30T09:00:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "Community", actorType: "community", note: "Verified by 18 community members.", date: "2026-05-30T11:00:00Z", completed: true },
      { step: "assigned", label: "Assigned", actor: "System", actorType: "system", note: "Auto-assigned to TMC Road Dept.", date: "2026-06-01T08:00:00Z", completed: true },
      { step: "in_progress", label: "In Progress", actor: "TMC Thane", actorType: "authority", note: "Emergency repair initiated.", date: "2026-06-06T14:00:00Z", completed: true },
      { step: "resolved", label: "Resolved", actor: "", actorType: "authority", note: "Pending completion.", date: null, completed: false },
    ],
  },
  {
    id: "rpt-011",
    reportId: "RPT-2026-00445",
    title: "Cluster of potholes on Nashik-Aurangabad road creating hazard",
    description:
      "Multiple potholes in 200m stretch. Buses swerving into oncoming traffic to avoid them.",
    hazardType: "pothole",
    hazardEmoji: "🕳",
    severity: "high",
    status: "submitted",
    statusStep: 1,
    location: {
      name: "Nashik Road",
      road: "Nashik-Aurangabad Highway",
      subdistrict: "Nashik Road",
      district: "Nashik",
      state: "Maharashtra",
      lat: 19.9457,
      lng: 73.8528,
      gps: "19.9457° N, 73.8528° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1611348586804-61bf6c080437?auto=format&fit=crop&w=800&q=85",
    photoCount: 2,
    upvotes: 34,
    hasUpvoted: false,
    comments: 7,
    views: 180,
    communityVerified: false,
    verificationCount: 1,
    isNotifying: false,
    createdAt: "2026-06-07T07:30:00Z",
    lastUpdatedAt: "2026-06-07T07:30:00Z",
    lastUpdatedBy: "Rahul M.",
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-06-07T07:30:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "", actorType: "community", note: "Awaiting community verification.", date: null, completed: false },
      { step: "assigned", label: "Assigned", actor: "", actorType: "system", note: "", date: null, completed: false },
      { step: "in_progress", label: "In Progress", actor: "", actorType: "authority", note: "", date: null, completed: false },
      { step: "resolved", label: "Resolved", actor: "", actorType: "authority", note: "", date: null, completed: false },
    ],
  },
  {
    id: "rpt-012",
    reportId: "RPT-2026-00256",
    title: "Recurring flooding at Kolhapur bus stand underpass",
    description:
      "Chronic flooding issue. Water reaches waist level during heavy rains. Public transport disrupted.",
    hazardType: "flooding",
    hazardEmoji: "🌊",
    severity: "medium",
    status: "resolved",
    statusStep: 5,
    location: {
      name: "Kolhapur City",
      road: "Bus Stand Underpass Road",
      subdistrict: "Kolhapur City",
      district: "Kolhapur",
      state: "Maharashtra",
      lat: 16.7050,
      lng: 74.2433,
      gps: "16.7050° N, 74.2433° E",
    },
    hasPhoto: true,
    photoUrl:
      "https://images.unsplash.com/photo-1596394723269-e1e8a86d3fd3?auto=format&fit=crop&w=800&q=85",
    photoCount: 1,
    upvotes: 76,
    hasUpvoted: true,
    comments: 14,
    views: 420,
    communityVerified: true,
    verificationCount: 9,
    isNotifying: false,
    createdAt: "2026-05-10T11:00:00Z",
    lastUpdatedAt: "2026-05-22T15:00:00Z",
    lastUpdatedBy: "KMC Kolhapur",
    assignedTo: "KMC Drainage Cell",
    referenceId: "KMC-2026-0234",
    officialResponse: {
      author: "KMC Kolhapur",
      isVerifiedAuthority: true,
      text: "New pumping station installed. Drainage capacity increased by 3x.",
      likes: 28,
      createdAt: "2026-05-22T15:00:00Z",
    },
    timeline: [
      { step: "submitted", label: "Submitted", actor: "Rahul M.", actorType: "citizen", note: "Report submitted successfully.", date: "2026-05-10T11:00:00Z", completed: true },
      { step: "verified", label: "Verified", actor: "Community", actorType: "community", note: "Verified by 9 community members.", date: "2026-05-10T13:00:00Z", completed: true },
      { step: "assigned", label: "Assigned", actor: "System", actorType: "system", note: "Auto-assigned to KMC Drainage Cell.", date: "2026-05-12T09:00:00Z", completed: true },
      { step: "in_progress", label: "In Progress", actor: "KMC Kolhapur", actorType: "authority", note: "New pumping station installation started.", date: "2026-05-15T10:00:00Z", completed: true },
      { step: "resolved", label: "Resolved", actor: "KMC Kolhapur", actorType: "authority", note: "New pumping station installed successfully.", date: "2026-05-22T15:00:00Z", completed: true },
    ],
  },
];

export const MOCK_STATS: UserStats = {
  totalReports: 12,
  openReports: 5,
  resolvedReports: 6,
  rejectedReports: 1,
  criticalReports: 3,
  totalUpvotes: 847,
  totalComments: 234,
  totalViews: 12400,
  resolutionRate: 50,
  rankPercentile: 5,
  rankArea: "Andheri West",
  hazardBreakdown: {
    pothole: 5,
    flooding: 3,
    accident: 2,
    signal: 1,
    debris: 1,
  },
  recentActivity: [
    { text: "BMC resolved your pothole report", timeAgo: "2h", type: "resolved" },
    { text: "Official responded to your flood report", timeAgo: "5h", type: "response" },
    { text: "Community verified your signal report", timeAgo: "1d", type: "verified" },
  ],
};
