import type { ComplaintRecord } from "@/store/complaintStore";

/** Initial complaint catalog — Panvel Taluka sub-district */
export const COMPLAINT_SEED: ComplaintRecord[] = [
  {
    id: "CMP-1024",
    title: "Severe Road Damage — Sector 7 Junction",
    description:
      "Large pothole spanning ~2m×1.5m at the main Sector 7 junction. Causes vehicle damage and safety hazard. Three accidents reported in the past week. Requires urgent patching and road resurfacing.",
    category: "Road Damage",
    priority: "Critical",
    status: "Assigned",
    location: "Sector 7, Panvel",
    coordinates: "18.9894° N, 73.1175° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone A",
    date: "2025-01-14",
    createdDate: "14 Jan 2025, 08:14 AM",
    updatedDate: "15 Jan 2025, 11:22 AM",
    officer: "R. Sharma",
    officerAssignedDate: "14 Jan 2025",
    expectedVisit: "16 Jan 2025",
    slaRisk: "High",
    supervisor: "District Officer K. Patil",
    slaStatus: "At Risk",
    slaLabel: "2h 14m Left",
    slaHours: 2.2,
    slaTargetHours: 48,
    resolutionTarget: "18 Jan 2025",
    reportCount: 3,
    nearbyCount: 2,
    resolutionStatus: "None",
    notes: "",
    evidenceCount: 3,
    timeline: [
      { label: "Complaint Created", date: "14 Jan, 08:14 AM", done: true, note: "Received via mobile app" },
      { label: "Assigned to Officer", date: "14 Jan, 09:30 AM", done: true, note: "Assigned to R. Sharma" },
      { label: "Site Inspection", date: "15 Jan, 10:00 AM", done: true, note: "Inspection completed" },
      { label: "Evidence Uploaded", date: "15 Jan, 11:22 AM", done: true, note: "3 photos added" },
      { label: "Awaiting Approval", date: "Pending", done: false, note: "" },
    ],
    activityLog: [
      { time: "15 Jan 11:45", actor: "R. Sharma", action: "Evidence uploaded — 3 site photos attached" },
      { time: "15 Jan 10:00", actor: "R. Sharma", action: "Site inspection completed. Pothole depth ~12cm." },
      { time: "14 Jan 09:30", actor: "System", action: "Complaint assigned to R. Sharma" },
      { time: "14 Jan 08:14", actor: "System", action: "Complaint received and registered" },
    ],
    evidence: {
      citizen: [{ label: "Front view", by: "Citizen Report", time: "14 Jan, 08:12 AM", coords: "18.9894° N" }],
      inspection: [
        { label: "Site overview", by: "R. Sharma", time: "15 Jan, 10:05 AM", coords: "18.9894° N" },
        { label: "Depth measure", by: "R. Sharma", time: "15 Jan, 10:12 AM", coords: "18.9894° N" },
      ],
      resolution: [],
    },
  },
  {
    id: "CMP-1023",
    title: "Waterlogging — Ward 3, Panvel",
    description:
      "Persistent waterlogging in Ward 3 near the market area. Water level reaches 8–10 inches during rain. Multiple vehicles have been damaged. Drain clearance and pump deployment needed.",
    category: "Waterlogging",
    priority: "High",
    status: "Assigned",
    location: "Ward 3, Panvel",
    coordinates: "18.9921° N, 73.1143° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone B",
    date: "2025-01-14",
    createdDate: "14 Jan 2025, 09:45 AM",
    updatedDate: "14 Jan 2025, 02:10 PM",
    officer: "P. Nair",
    officerAssignedDate: "14 Jan 2025",
    expectedVisit: "15 Jan 2025",
    slaRisk: "Medium",
    supervisor: "District Officer K. Patil",
    slaStatus: "At Risk",
    slaLabel: "6h Left",
    slaHours: 6,
    slaTargetHours: 48,
    resolutionTarget: "17 Jan 2025",
    reportCount: 5,
    nearbyCount: 1,
    resolutionStatus: "None",
    notes: "",
    evidenceCount: 1,
    timeline: [
      { label: "Complaint Created", date: "14 Jan, 09:45 AM", done: true, note: "Received via mobile app" },
      { label: "Assigned to Officer", date: "14 Jan, 11:00 AM", done: true, note: "Assigned to P. Nair" },
      { label: "Site Inspection", date: "Scheduled", done: false, note: "" },
      { label: "Awaiting Approval", date: "Pending", done: false, note: "" },
    ],
    activityLog: [
      { time: "14 Jan 11:00", actor: "System", action: "Complaint assigned to P. Nair" },
      { time: "14 Jan 09:45", actor: "System", action: "Complaint received and registered" },
    ],
    evidence: {
      citizen: [{ label: "Street view", by: "Citizen Report", time: "14 Jan, 09:40 AM", coords: "18.9921° N" }],
      inspection: [],
      resolution: [],
    },
  },
  {
    id: "CMP-1022",
    title: "Streetlight Outage — NH-48 Junction",
    description:
      "Three consecutive streetlights are non-functional at the NH-48 junction. The area is a known accident-prone zone. Electrical fault suspected. Night-time visibility is critically low.",
    category: "Streetlight",
    priority: "Medium",
    status: "In Progress",
    location: "NH-48 Junction",
    coordinates: "18.9876° N, 73.1200° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone C",
    date: "2025-01-13",
    createdDate: "13 Jan 2025, 07:30 PM",
    updatedDate: "14 Jan 2025, 10:15 AM",
    officer: "A. Kulkarni",
    officerAssignedDate: "13 Jan 2025",
    expectedVisit: "14 Jan 2025",
    slaRisk: "Low",
    supervisor: "District Officer K. Patil",
    slaStatus: "On Track",
    slaLabel: "20h Left",
    slaHours: 20,
    slaTargetHours: 48,
    resolutionTarget: "19 Jan 2025",
    reportCount: 2,
    nearbyCount: 0,
    resolutionStatus: "None",
    notes: "",
    evidenceCount: 2,
    timeline: [
      { label: "Complaint Created", date: "13 Jan, 07:30 PM", done: true, note: "Received via mobile app" },
      { label: "Assigned to Officer", date: "13 Jan, 08:00 PM", done: true, note: "Assigned to A. Kulkarni" },
      { label: "Site Inspection", date: "14 Jan, 10:00 AM", done: true, note: "Fault identified" },
      { label: "Work In Progress", date: "14 Jan, 10:15 AM", done: true, note: "Repair crew dispatched" },
      { label: "Awaiting Approval", date: "Pending", done: false, note: "" },
    ],
    activityLog: [
      { time: "14 Jan 10:15", actor: "A. Kulkarni", action: "Repair crew dispatched to site" },
      { time: "14 Jan 10:00", actor: "A. Kulkarni", action: "Electrical fault confirmed — 3 units affected" },
      { time: "13 Jan 08:00", actor: "System", action: "Complaint assigned to A. Kulkarni" },
      { time: "13 Jan 19:30", actor: "System", action: "Complaint received and registered" },
    ],
    evidence: {
      citizen: [{ label: "Dark junction", by: "Citizen Report", time: "13 Jan, 07:28 PM", coords: "18.9876° N" }],
      inspection: [{ label: "Faulty unit", by: "A. Kulkarni", time: "14 Jan, 10:08 AM", coords: "18.9876° N" }],
      resolution: [],
    },
  },
  {
    id: "CMP-1021",
    title: "Sewage Overflow — Sector 12",
    description:
      "Sewage overflow at the main drain junction in Sector 12. Raw sewage on the street poses serious health hazard. Residents in three buildings affected. Immediate drain clearance required.",
    category: "Sewage",
    priority: "High",
    status: "Open",
    location: "Sector 12, Panvel",
    coordinates: "18.9903° N, 73.1162° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone A",
    date: "2025-01-13",
    createdDate: "13 Jan 2025, 11:20 AM",
    updatedDate: "13 Jan 2025, 11:20 AM",
    officer: "M. Patil",
    officerAssignedDate: "13 Jan 2025",
    expectedVisit: "14 Jan 2025",
    slaRisk: "High",
    supervisor: "District Officer K. Patil",
    slaStatus: "At Risk",
    slaLabel: "4h Left",
    slaHours: 4,
    slaTargetHours: 48,
    resolutionTarget: "16 Jan 2025",
    reportCount: 4,
    nearbyCount: 2,
    resolutionStatus: "None",
    notes: "",
    evidenceCount: 1,
    timeline: [
      { label: "Complaint Created", date: "13 Jan, 11:20 AM", done: true, note: "Received via mobile app" },
      { label: "Assigned to Officer", date: "13 Jan, 12:00 PM", done: true, note: "Assigned to M. Patil" },
      { label: "Site Inspection", date: "Pending", done: false, note: "" },
    ],
    activityLog: [
      { time: "13 Jan 12:00", actor: "System", action: "Complaint assigned to M. Patil" },
      { time: "13 Jan 11:20", actor: "System", action: "Complaint received and registered" },
    ],
    evidence: {
      citizen: [{ label: "Overflow view", by: "Citizen Report", time: "13 Jan, 11:15 AM", coords: "18.9903° N" }],
      inspection: [],
      resolution: [],
    },
  },
  {
    id: "CMP-1020",
    title: "Garbage Dump — Market Road",
    description:
      "Illegal garbage dump formed near Market Road bus stop. Waste has been accumulating for 5 days. Flies and rodents visible. Health hazard for nearby vendors and pedestrians.",
    category: "Garbage",
    priority: "Medium",
    status: "Resolved",
    location: "Market Road, Panvel",
    coordinates: "18.9887° N, 73.1190° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone B",
    date: "2025-01-12",
    createdDate: "12 Jan 2025, 03:10 PM",
    updatedDate: "14 Jan 2025, 05:00 PM",
    officer: "S. Desai",
    officerAssignedDate: "12 Jan 2025",
    expectedVisit: "13 Jan 2025",
    slaRisk: "Low",
    supervisor: "District Officer K. Patil",
    slaStatus: "On Track",
    slaLabel: "Resolved",
    slaHours: 99,
    slaTargetHours: 48,
    resolutionTarget: "15 Jan 2025",
    reportCount: 2,
    nearbyCount: 0,
    resolutionStatus: "Approved",
    notes: "",
    evidenceCount: 3,
    timeline: [
      { label: "Complaint Created", date: "12 Jan, 03:10 PM", done: true, note: "Received via mobile app" },
      { label: "Assigned to Officer", date: "12 Jan, 04:00 PM", done: true, note: "Assigned to S. Desai" },
      { label: "Site Inspection", date: "13 Jan, 09:30 AM", done: true, note: "Site assessed" },
      { label: "Work In Progress", date: "13 Jan, 02:00 PM", done: true, note: "Clearance crew on-site" },
      { label: "Resolved", date: "14 Jan, 05:00 PM", done: true, note: "Area fully cleared" },
    ],
    activityLog: [
      { time: "14 Jan 17:00", actor: "S. Desai", action: "Garbage cleared — area sanitised and verified" },
      { time: "13 Jan 14:00", actor: "S. Desai", action: "Clearance crew dispatched to Market Road" },
      { time: "13 Jan 09:30", actor: "S. Desai", action: "Site inspection completed" },
      { time: "12 Jan 16:00", actor: "System", action: "Complaint assigned to S. Desai" },
      { time: "12 Jan 15:10", actor: "System", action: "Complaint received and registered" },
    ],
    evidence: {
      citizen: [{ label: "Dump site", by: "Citizen Report", time: "12 Jan, 03:05 PM", coords: "18.9887° N" }],
      inspection: [{ label: "Assessment", by: "S. Desai", time: "13 Jan, 09:35 AM", coords: "18.9887° N" }],
      resolution: [{ label: "Post-clear", by: "S. Desai", time: "14 Jan, 05:05 PM", coords: "18.9887° N" }],
    },
  },
  {
    id: "CMP-1019",
    title: "Road Damage — Old Panvel Road",
    description:
      "Multiple large potholes and a collapsed road edge on Old Panvel Road near the railway bridge. Heavy vehicles frequently use this route. Two accidents reported this week.",
    category: "Road Damage",
    priority: "Critical",
    status: "Assigned",
    location: "Old Panvel Road",
    coordinates: "18.9932° N, 73.1130° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone C",
    date: "2025-01-12",
    createdDate: "12 Jan 2025, 10:00 AM",
    updatedDate: "12 Jan 2025, 01:30 PM",
    officer: "R. Sharma",
    officerAssignedDate: "12 Jan 2025",
    expectedVisit: "13 Jan 2025",
    slaRisk: "Critical",
    supervisor: "District Officer K. Patil",
    slaStatus: "Breached",
    slaLabel: "BREACHED",
    slaHours: -12,
    slaTargetHours: 48,
    resolutionTarget: "15 Jan 2025",
    reportCount: 4,
    nearbyCount: 3,
    resolutionStatus: "None",
    notes: "",
    evidenceCount: 1,
    timeline: [
      { label: "Complaint Created", date: "12 Jan, 10:00 AM", done: true, note: "Received via mobile app" },
      { label: "Assigned to Officer", date: "12 Jan, 01:30 PM", done: true, note: "Assigned to R. Sharma" },
      { label: "Site Inspection", date: "Overdue", done: false, note: "" },
    ],
    activityLog: [
      { time: "12 Jan 13:30", actor: "System", action: "Complaint assigned to R. Sharma" },
      { time: "12 Jan 10:00", actor: "System", action: "Complaint received and registered" },
    ],
    evidence: {
      citizen: [{ label: "Road collapse", by: "Citizen Report", time: "12 Jan, 09:55 AM", coords: "18.9932° N" }],
      inspection: [],
      resolution: [],
    },
  },
  {
    id: "CMP-1018",
    title: "Water Supply Disruption — Sector 5",
    description: "Intermittent water supply failure reported across Sector 5 residential blocks.",
    category: "Water Supply",
    priority: "High",
    status: "In Progress",
    location: "Sector 5, Panvel",
    coordinates: "18.9910° N, 73.1155° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone A",
    date: "2025-01-11",
    createdDate: "11 Jan 2025, 09:00 AM",
    updatedDate: "11 Jan 2025, 02:00 PM",
    officer: "P. Nair",
    officerAssignedDate: "11 Jan 2025",
    expectedVisit: "12 Jan 2025",
    slaRisk: "Medium",
    supervisor: "District Officer K. Patil",
    slaStatus: "On Track",
    slaLabel: "18h Left",
    slaHours: 18,
    slaTargetHours: 48,
    resolutionTarget: "14 Jan 2025",
    reportCount: 2,
    nearbyCount: 0,
    resolutionStatus: "None",
    notes: "",
    evidenceCount: 0,
    timeline: [{ label: "Complaint Created", date: "11 Jan, 09:00 AM", done: true, note: "Received via mobile app" }],
    activityLog: [{ time: "11 Jan 09:00", actor: "System", action: "Complaint received and registered" }],
    evidence: { citizen: [], inspection: [], resolution: [] },
  },
  {
    id: "CMP-1017",
    title: "Fallen Tree — Near Station",
    description: "Large tree branch obstructing footpath near Panvel station entrance.",
    category: "Tree Fallen",
    priority: "Medium",
    status: "Resolved",
    location: "Near Station",
    coordinates: "18.9898° N, 73.1188° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone B",
    date: "2025-01-11",
    createdDate: "11 Jan 2025, 07:30 AM",
    updatedDate: "12 Jan 2025, 04:00 PM",
    officer: "A. Kulkarni",
    officerAssignedDate: "11 Jan 2025",
    expectedVisit: "11 Jan 2025",
    slaRisk: "Low",
    supervisor: "District Officer K. Patil",
    slaStatus: "On Track",
    slaLabel: "Resolved",
    slaHours: 99,
    slaTargetHours: 48,
    resolutionTarget: "13 Jan 2025",
    reportCount: 1,
    nearbyCount: 0,
    resolutionStatus: "Approved",
    notes: "",
    evidenceCount: 1,
    timeline: [{ label: "Resolved", date: "12 Jan, 04:00 PM", done: true, note: "Branch cleared" }],
    activityLog: [{ time: "12 Jan 16:00", actor: "A. Kulkarni", action: "Tree branch removed and area cleared" }],
    evidence: { citizen: [], inspection: [], resolution: [{ label: "Cleared site", by: "A. Kulkarni", time: "12 Jan, 04:05 PM", coords: "18.9898° N" }] },
  },
  {
    id: "CMP-1016",
    title: "Noise Pollution — Sector 9",
    description: "Construction noise exceeding permitted hours in Sector 9 residential zone.",
    category: "Noise Pollution",
    priority: "Low",
    status: "Open",
    location: "Sector 9, Panvel",
    coordinates: "18.9865° N, 73.1210° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone C",
    date: "2025-01-10",
    createdDate: "10 Jan 2025, 10:00 PM",
    updatedDate: "10 Jan 2025, 10:00 PM",
    officer: "",
    officerAssignedDate: "—",
    expectedVisit: "—",
    slaRisk: "Low",
    supervisor: "District Officer K. Patil",
    slaStatus: "On Track",
    slaLabel: "36h Left",
    slaHours: 36,
    slaTargetHours: 72,
    resolutionTarget: "13 Jan 2025",
    reportCount: 1,
    nearbyCount: 0,
    resolutionStatus: "None",
    notes: "",
    evidenceCount: 0,
    timeline: [{ label: "Complaint Created", date: "10 Jan, 10:00 PM", done: true, note: "Received via mobile app" }],
    activityLog: [{ time: "10 Jan 22:00", actor: "System", action: "Complaint received and registered" }],
    evidence: { citizen: [], inspection: [], resolution: [] },
  },
  {
    id: "CMP-1015",
    title: "Sewage Blockage — Ward 6",
    description: "Blocked sewage line causing backup in Ward 6 lane 4.",
    category: "Sewage",
    priority: "High",
    status: "Rejected",
    location: "Ward 6, Panvel",
    coordinates: "18.9908° N, 73.1148° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone A",
    date: "2025-01-10",
    createdDate: "10 Jan 2025, 08:00 AM",
    updatedDate: "11 Jan 2025, 09:00 AM",
    officer: "M. Patil",
    officerAssignedDate: "10 Jan 2025",
    expectedVisit: "10 Jan 2025",
    slaRisk: "High",
    supervisor: "District Officer K. Patil",
    slaStatus: "Breached",
    slaLabel: "BREACHED",
    slaHours: -8,
    slaTargetHours: 48,
    resolutionTarget: "12 Jan 2025",
    reportCount: 2,
    nearbyCount: 1,
    resolutionStatus: "Rejected",
    notes: "Duplicate complaint — already tracked under CMP-1021",
    evidenceCount: 0,
    timeline: [{ label: "Rejected", date: "11 Jan, 09:00 AM", done: true, note: "Duplicate entry" }],
    activityLog: [{ time: "11 Jan 09:00", actor: "Officer", action: "Complaint rejected — duplicate of CMP-1021" }],
    evidence: { citizen: [], inspection: [], resolution: [] },
  },
  {
    id: "CMP-1014",
    title: "Critical Potholes — Highway 17",
    description: "Cluster of critical potholes on Highway 17 affecting heavy traffic.",
    category: "Road Damage",
    priority: "Critical",
    status: "Resolved",
    location: "Highway 17",
    coordinates: "18.9945° N, 73.1120° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone C",
    date: "2025-01-09",
    createdDate: "09 Jan 2025, 06:00 AM",
    updatedDate: "10 Jan 2025, 06:00 PM",
    officer: "R. Sharma",
    officerAssignedDate: "09 Jan 2025",
    expectedVisit: "09 Jan 2025",
    slaRisk: "Low",
    supervisor: "District Officer K. Patil",
    slaStatus: "On Track",
    slaLabel: "Resolved",
    slaHours: 99,
    slaTargetHours: 48,
    resolutionTarget: "11 Jan 2025",
    reportCount: 3,
    nearbyCount: 2,
    resolutionStatus: "Approved",
    notes: "",
    evidenceCount: 2,
    timeline: [{ label: "Resolved", date: "10 Jan, 06:00 PM", done: true, note: "Road resurfaced" }],
    activityLog: [{ time: "10 Jan 18:00", actor: "R. Sharma", action: "Highway 17 potholes patched and verified" }],
    evidence: { citizen: [], inspection: [{ label: "Patch work", by: "R. Sharma", time: "10 Jan, 05:30 PM", coords: "18.9945° N" }], resolution: [] },
  },
  {
    id: "CMP-1013",
    title: "Waterlogging — Taluka Office Road",
    description: "Standing water on Taluka Office Road after rainfall — drainage blocked.",
    category: "Waterlogging",
    priority: "Medium",
    status: "Open",
    location: "Taluka Office Road",
    coordinates: "18.9880° N, 73.1170° E",
    subDistrict: "Panvel Taluka",
    zone: "Zone B",
    date: "2025-01-09",
    createdDate: "09 Jan 2025, 11:00 AM",
    updatedDate: "09 Jan 2025, 11:00 AM",
    officer: "S. Desai",
    officerAssignedDate: "09 Jan 2025",
    expectedVisit: "10 Jan 2025",
    slaRisk: "Medium",
    supervisor: "District Officer K. Patil",
    slaStatus: "At Risk",
    slaLabel: "8h Left",
    slaHours: 8,
    slaTargetHours: 48,
    resolutionTarget: "12 Jan 2025",
    reportCount: 1,
    nearbyCount: 0,
    resolutionStatus: "None",
    notes: "",
    evidenceCount: 0,
    timeline: [{ label: "Complaint Created", date: "09 Jan, 11:00 AM", done: true, note: "Received via mobile app" }],
    activityLog: [{ time: "09 Jan 11:00", actor: "System", action: "Complaint received and registered" }],
    evidence: { citizen: [], inspection: [], resolution: [] },
  },
];
