import type { WorkTicket } from "@/store/complaintWorkflowStore";

export const TICKET_SEED: WorkTicket[] = [
  {
    id: "TKT-0501",
    complaintId: "CMP-1024",
    title: "Road Resurfacing — Sector 7 Junction",
    description:
      "Complete resurfacing of the damaged road section at Sector 7 junction. Includes pothole filling, base layer repair, and top coat application.",
    team: "Road Crew Alpha",
    assignedOfficer: "V. Kamble",
    teamLead: "V. Kamble",
    teamMembers: ["R. More", "S. Jadhav", "A. Pawar"],
    teamContact: "+91 98123 45678",
    priority: "Critical",
    status: "In Progress",
    created: "2025-01-14",
    due: "2025-01-16",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes:
      "Site survey completed. Pothole depth measured at 15cm. Requires full base layer repair before resurfacing. Area cordoned off with cones.",
    timeline: [
      { label: "Ticket Created", time: "Jan 14, 09:30 AM", done: true },
      { label: "Team Assigned", time: "Jan 14, 10:15 AM", done: true },
      { label: "Material Procurement", time: "Jan 14, 02:00 PM", done: true },
      { label: "Work In Progress", time: "Jan 15, 08:00 AM", done: true },
      { label: "Inspection & Sign-off", time: "Jan 16 — Pending", done: false },
    ],
    materials: [
      { item: "Bitumen (Grade 60/70)", qty: "200 kg", cost: "₹12,000" },
      { item: "Aggregate (10mm)", qty: "500 kg", cost: "₹4,500" },
    ],
    attachments: [
      { name: "Site_Survey_TKT0501.pdf", size: "2.1 MB" },
      { name: "Pre-work_Photo.jpg", size: "3.4 MB" },
    ],
  },
  {
    id: "TKT-0500",
    complaintId: "CMP-1021",
    title: "Sewage drain clearance — Sector 12",
    description: "Emergency drain clearance and sanitation treatment for sewage overflow complaint.",
    team: "Sanitation Unit B",
    assignedOfficer: "M. Patil",
    priority: "High",
    status: "In Progress",
    created: "2025-01-14",
    due: "2025-01-17",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes: "",
    timeline: [
      { label: "Ticket Created", time: "Jan 14, 11:00 AM", done: true },
      { label: "Team Assigned", time: "Jan 14, 12:00 PM", done: true },
      { label: "Work In Progress", time: "Jan 15, 08:00 AM", done: true },
      { label: "Inspection & Sign-off", time: "Pending", done: false },
    ],
  },
  {
    id: "TKT-0499",
    complaintId: "CMP-1019",
    title: "Road repair — Old Panvel Road",
    description: "Pothole cluster repair and road edge stabilization near railway bridge.",
    team: "Road Crew Alpha",
    assignedOfficer: "R. Sharma",
    priority: "Critical",
    status: "Overdue",
    created: "2025-01-12",
    due: "2025-01-14",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes: "SLA breached — awaiting additional crew allocation.",
    timeline: [
      { label: "Ticket Created", time: "Jan 12, 10:30 AM", done: true },
      { label: "Team Assigned", time: "Jan 12, 01:30 PM", done: true },
      { label: "Work In Progress", time: "Overdue", done: false },
    ],
  },
  {
    id: "TKT-0498",
    complaintId: "CMP-1018",
    title: "Water supply line inspection",
    description: "Inspect and repair intermittent water supply in Sector 5.",
    team: "Utilities Team",
    assignedOfficer: "P. Nair",
    priority: "High",
    status: "In Progress",
    created: "2025-01-11",
    due: "2025-01-15",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes: "",
    timeline: [
      { label: "Ticket Created", time: "Jan 11, 09:00 AM", done: true },
      { label: "Team Assigned", time: "Jan 11, 10:00 AM", done: true },
      { label: "Work In Progress", time: "Jan 12, 08:00 AM", done: true },
    ],
  },
  {
    id: "TKT-0497",
    complaintId: "CMP-1017",
    title: "Tree removal — Near Station",
    description: "Remove fallen tree branch obstructing footpath.",
    team: "Horticulture Unit",
    assignedOfficer: "A. Kulkarni",
    priority: "Medium",
    status: "Completed",
    created: "2025-01-11",
    due: "2025-01-18",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes: "Work completed and verified.",
    timeline: [
      { label: "Ticket Created", time: "Jan 11, 07:30 AM", done: true },
      { label: "Team Assigned", time: "Jan 11, 08:00 AM", done: true },
      { label: "Work Completed", time: "Jan 12, 04:00 PM", done: true },
    ],
  },
  {
    id: "TKT-0496",
    complaintId: "CMP-1022",
    title: "Streetlight repair — NH-48 Junction",
    description: "Replace faulty electrical units at junction.",
    team: "Electrical Crew",
    assignedOfficer: "A. Kulkarni",
    priority: "Medium",
    status: "In Progress",
    created: "2025-01-13",
    due: "2025-01-19",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes: "",
    timeline: [
      { label: "Ticket Created", time: "Jan 13, 08:00 PM", done: true },
      { label: "Team Assigned", time: "Jan 14, 09:00 AM", done: true },
      { label: "Work In Progress", time: "Jan 14, 10:15 AM", done: true },
    ],
  },
  {
    id: "TKT-0495",
    complaintId: "CMP-1016",
    title: "Noise pollution inspection",
    description: "Site visit and compliance notice for construction noise.",
    team: "Inspection Unit",
    assignedOfficer: "S. Desai",
    priority: "Low",
    status: "Open",
    created: "2025-01-10",
    due: "2025-01-20",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes: "",
    timeline: [{ label: "Ticket Created", time: "Jan 10, 10:00 PM", done: true }],
  },
  {
    id: "TKT-0494",
    complaintId: "CMP-1023",
    title: "Drainage pump deployment — Ward 3",
    description: "Deploy pumps and clear waterlogging near market area.",
    team: "Road Crew Beta",
    assignedOfficer: "P. Nair",
    priority: "High",
    status: "Open",
    created: "2025-01-14",
    due: "2025-01-16",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes: "",
    timeline: [
      { label: "Ticket Created", time: "Jan 14, 09:45 AM", done: true },
      { label: "Team Assigned", time: "Jan 14, 11:00 AM", done: true },
    ],
  },
  {
    id: "TKT-0493",
    complaintId: "CMP-1013",
    title: "Drainage clearance — Taluka Office Road",
    description: "Clear blocked drainage causing standing water.",
    team: "Drainage Team",
    assignedOfficer: "S. Desai",
    priority: "Medium",
    status: "In Progress",
    created: "2025-01-09",
    due: "2025-01-17",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes: "",
    timeline: [
      { label: "Ticket Created", time: "Jan 09, 11:00 AM", done: true },
      { label: "Work In Progress", time: "Jan 10, 08:00 AM", done: true },
    ],
  },
  {
    id: "TKT-0492",
    complaintId: "CMP-1014",
    title: "Highway pothole repair — Highway 17",
    description: "Critical pothole cluster patching on Highway 17.",
    team: "Road Crew Alpha",
    assignedOfficer: "R. Sharma",
    priority: "Critical",
    status: "Completed",
    created: "2025-01-09",
    due: "2025-01-11",
    submittedBy: "Sub-District Officer",
    subDistrict: "Panvel Taluka",
    notes: "Completed ahead of schedule.",
    timeline: [
      { label: "Ticket Created", time: "Jan 09, 06:00 AM", done: true },
      { label: "Work Completed", time: "Jan 10, 06:00 PM", done: true },
    ],
  },
];
